### ISSUE TITLE
Workload identity sidecars are not supported for Windows containers

### ISSUE THREAD

**Issue by Meertman** [Azure/azure-workload-identity#1017]
**Describe the bug**
As mentioned into my previous issue https://github.com/Azure/azure-workload-identity/issues/1016, when trying to use the sidecars for our application running on a Windows container, the images failed to be pulled, with the following message:
`Failed to pull image "mcr.microsoft.com/oss/azure/workload-identity/proxy-init:v1.0.0": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/oss/azure/workload-identity/proxy-init:v1.0.0": no match for platform in manifest: not found`

If this is expected behavior, it might be nice to document this somewhere as I could not find this anywhere on this page: https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity#deploy-the-workload-with-migration-sidecar

**Environment**

- Kubernetes version (use kubectl version): v1.26.3
- Cloud provider or hardware configuration: Azure
- OS (e.g: cat /etc/os-release): Windows 10 - mcr.microsoft.com/windows:1809

**Comment by aramase** [comment]
> If this is expected behavior, it might be nice to document this somewhere as I could not find this anywhere on this page:

The proxy sidecar container is a way for current pod identity users to migrate to workload identity. The proxy is only for Linux containers as pod identity only supported Linux.

Thanks for the feedback on the doc. I've opened an internal PR to get the doc updated!
