### ISSUE TITLE
Restrict access to a secret(particualr secret) in Keyvault

### ISSUE THREAD

**Issue by ashishstationcasinos** [Azure/azure-workload-identity#1043]
Hello 

I have a keyvault. It has 40 secrets. I did configured managed identity to get the vaule of the secret. Now I want to restrict the access to that particalur secret for the users in the AD.

Is there a way I can Create a ROLE  where it can create/delete/update/purge secrets but can't read the vaule of a PARTICAULR SECRET in the keyvault ? please suggest

**Comment by aramase** [comment]
@ashishstationcasinos The rbac permissions you're looking for should be in the key vault docs: https://learn.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli.

I'm going to close this issue as it's not directly related to workload identity. Hope the doc helps! Feel free to reach out if you have any questions related to usage of workload identity.
