### ISSUE TITLE
Support for GitHub OIDC job_workflow_ref claim

### ISSUE THREAD

**Issue by dghubble** [Azure/azure-workload-identity#1048]
**Is your feature request related to a problem? Please describe.**

GitHub OIDC supports many custom claims that would be very valuable with Azure Federated Identity, in particular the `job_workflow_ref`. 

**Describe the solution you'd like**

Azure AD allows workloads to access Azure resources using Federated Identity credentials, like using GitHub OIDC to let GitHub Workflows access Azure resources. Today, subject attribute matching allows validating that a GitHub OIDC token came from a specific organization and repo. Within that, only a few fixed options are available:

![Screenshot 2023-08-03 at 6 27 11 PM](https://github.com/Azure/azure-workload-identity/assets/2253428/d15cca99-264c-4a57-822b-4df234ec78b7)

Support for the `job_workflow_ref` field would be especially valuable because repos may have many workflows. Such an attribute matcher could allow limiting specific workflows and revisions to being able to assume Azure Federated Identities.

```
"job_workflow_ref": "octo-org/octo-automation/.github/workflows/oidc.yml@refs/heads/main",
```

Broadly, it would be nice to have more flexibility in crafting the exact subject attributes we wish to match on. AWS allows StringLike comparisons and Google Cloud allows CEL expressions.

**Describe alternatives you've considered**

Using static credentials

**Additional context**

GitHub Docs: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token

**Comment by aramase** [comment]
@dghubble Thank you for opening the issue. This repo is specifically for workload identity in Kubernetes. I see you have started a thread internally and this feature request is for AAD Workload Identity support with the GitHub workflow, so I'm going to close this issue.

**Comment by pdxjohnny** [comment]
@aramase Are there any docs for AAD Workload Identity support with the GitHub workflow at this point?

**Comment by josnyder-2** [comment]
Good news: this is supported by federated identity today 

```
az rest -m POST -u "https://graph.microsoft.com/beta/applications/APPLICATION_OBJECT_ID/federatedIdentityCredentials/" --body "$(< /dev/stdin)"
{
  "audiences": [
    "api://AzureADTokenExchange"
  ],
  "issuer": "https://token.actions.githubusercontent.com",
  "name": "test",
  "claimsMatchingExpression": {
    "languageVersion": 1,
    "value": "claims['sub'] eq 'repo:ORG/REPO:pull_request:head_ref:MYBRANCH' and claims['workflow_ref'] startswith 'ORG/REPO/.github/workflows/WORKFLOW_FILENAME@refs/pull/PR_NUMBER/merge'"
  }
}
```

Bad news: only the `eq` operator is supported on `workflow_ref`, and not `startswith`.
