### ISSUE TITLE
Use inject-proxy-sidecar and hostNetwork together will cause host iptables to be updated

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-workload-identity#1050]
**Describe the bug**
If a pod uses both inject-proxy-sidecar and hostNetwork, the iptables on host will be updated. This might lead to strange behavior. Any call to the node IMDS will redirect to the wi proxy.

Suggest to call out in doc this is not supported.

**Steps To Reproduce**
Create a pod with both inject-proxy-sidecar and hostNetwork.

**Expected behavior**

**Logs**
Following entry will appear on host node:
`-A OUTPUT -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j AZWI_PROXY_OUTPUT`

**Environment**

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by aramase** [comment]
closed with https://github.com/Azure/azure-workload-identity/pull/1090
