### ISSUE TITLE
KubeApi server cannot reach the OIDC ENDPOINT URL

### ISSUE THREAD

**Issue by ashishreddyaleti** [Azure/azure-workload-identity#1130]
I have Nutanix Kubernetes Cluster. I did Followed the Documnetaion to Implement the Workload Identity on Nutanix Cluster. 

As part of the Self Managed Cluster, 
  1. I did create Private keys and Public keys (signing key pairs)
  2.  Manually Created OIDC issuer URL and Uploaded the Discovery Document and JWKS to public endpoint with Storage Account with a Container.
  3.  When My Storage Account has Public Access (Enabled from All Networks), The services deployed in Kubernetes Cluster can access azure Resources

 But When I configure Storage account to Enable access from Particular Networks, Services/Pods are cashing with below error 

AggregateAuthenticationError: ChainedTokenCredential authentication failed.
CredentialUnavailableError: EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot.
AuthenticationRequiredError: invalid_request: 50166 - [2023-10-03 00:44:32Z]: AADSTS50166: Request to External OIDC endpoint failed.
Trace ID: 4b3babc2-dcd3-4e6f-8fe0-7d1ec15d3600
Correlation ID: 09cb4760-c7b8-4567-a79a-83fff7a750ca
Timestamp: 2023-10-03 00:44:32Z - Correlation ID: 09cb4760-c7b8-4567-a79a-83fff7a750ca - Trace ID: 4b3babc2-dcd3-4e6f-8fe0-7d1ec15d3600
AuthenticationRequiredError: invalid_request: 50166 - [2023-10-03 00:44:33Z]: AADSTS50166: Request to External OIDC endpoint failed.

I tried to to curl command to Service account issuer url from the Master Nodes and Worked node of Kubernetes. they are able to reach the URL. and Even Tested from a Pod with Curl command it is reachbale.  Not sure why the APIServer is not reaching the External OIDC Endpoint when I configure Storage networking access from a particular networks.

Please help me How can I sort out this Issue ? Any help will be Appreciated.

Thanks

**Comment by aramase** [comment]
This is documented in the troubleshooting guide: https://azure.github.io/azure-workload-identity/docs/troubleshooting.html#aadsts90061-request-to-external-oidc-endpoint-failed. Please refer to the steps in the doc to confirm the endpoint is publicly accessible. 

> Even Tested from a Pod with Curl command it is reachbale. Not sure why the APIServer is not reaching the External OIDC Endpoint when I configure Storage networking access from a particular networks.

The Kubernetes API server doesn't reach out to the Service account issuer url. The endpoint needs to be accessible by AAD.

Closing this issue with troubleshooting guide steps.
