### ISSUE TITLE
Workload identity does not support First Party Apps?

### ISSUE THREAD

**Issue by djj0809** [Azure/azure-workload-identity#1274]
**Describe the bug**

# Background
We are internal Azure team, recently we are asked to move away from client certificates which we use to auth with 3rd party apps and first party apps, and the only option is to use federated identity. We primarily use AKS to host our services so we started to see if we can enable federated identity integration (We already enabled workload identity on our clusters with user assigned managed identity).

However I did some experiments and found out that it seems does not work with first party apps (followed https://review.learn.microsoft.com/en-us/identity/microsoft-identity-platform/federated-identity-credentials?branch=main#register-a-federated-identity-credential), I received below error, since the token is issued by AKS cluster, I cannot use it with first party app?  The doc does mention that, so I believe token issued from AKS cluster is not supported: 

> First-party applications can be configured to accept these access tokens as a credential when issued by certain Microsoft Entra tenants (For example, AME and PME) and when the token’s subject is an Azure Managed Identity.

`
{"error":"invalid_client","error_description":"AADSTS700223: **Only AAD-issued tokens may be used for first-party application federated identity flows**. Trace ID: 22141a72-da35-45a4-9290-3d5d8bc15001 Correlation ID: 51e4a297-bf34-4dd3-8e33-f225c0966f88 Timestamp: 2024-02-29 22:52:50Z","error_codes":[700223],"timestamp":"2024-02-29 22:52:50Z","trace_id":"22141a72-da35-45a4-9290-3d5d8bc15001","correlation_id":"51e4a297-bf34-4dd3-8e33-f225c0966f88","error_uri":"https://eastus2.login.microsoft.com/error?code=700223"}
`

I also tried to "chain" them, get the token from MSI using workload identity first, and then use the token to auth with first party app, it's failed with another error:
`{"error":"invalid_client","error_description":"AADSTS700231: Token obtained using another federated identity credential may not be used as federated identity credential. Trace ID: 1b9234de-cfb1-419f-ae01-ceb29a057201 Correlation ID: f7d424f0-8c47-40b0-9af1-6cb9626dc4fb Timestamp: 2024-03-01 22:12:15Z","error_codes":[700231],"timestamp":"2024-03-01 22:12:15Z","trace_id":"1b9234de-cfb1-419f-ae01-ceb29a057201","correlation_id":"f7d424f0-8c47-40b0-9af1-6cb9626dc4fb"} 
`
Could you confirm if it is the case? If it is, is there any alternative way to do it? It seems that we cannot use this feature after switching to workload identity.

**Comment by djj0809** [comment]
>

**Comment by prateekprshr-nith** [comment]
@djj0809 we are also an Azure internal team and getting into the same issue. Did you find a solution?

**Comment by djj0809** [comment]
@prateekprshr-nith I haven't

**Comment by nickludwig** [comment]
@djj0809/@prateekprshr-nith - can you folks ping me internally? This is a public facing thread. All discussions surrounding 1P focused stuff should be kept internal.

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/azure-workload-identity/issues/1274#issuecomment-2007890427.
