### ISSUE TITLE
mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.2.1: not found

### ISSUE THREAD

**Issue by chase-miller** [Azure/azure-workload-identity#1281]
**Describe the bug**

**Steps To Reproduce**
1. Execute `helm install -n azure-workload-identity-system workload-identity-webhook azure-workload-identity/workload-identity-webhook --set azureTenantID=<tenant-id> --create-namespace`

**Expected behavior**
Pods are spun up successfully

**Logs**
> Failed to pull image "mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.2.1": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.2.1": failed to resolve reference "mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.2.1": mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.2.1: not found

**Environment**

- Kubernetes version (use `kubectl version`): v1.29.1
- Cloud provider or hardware configuration: M1 Pro MacBook
- OS (e.g: `cat /etc/os-release`): macOS 14.3.1
- Kernel (e.g. `uname -a`): `23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64`
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**
According to [this page](https://artifacthub.io/packages/helm/azure-workload-identity/workload-identity-webhook) the helm chart was updated today. I also noticed [this error](https://github.com/Azure/azure-workload-identity/actions/runs/8161087425/job/22309510635#step:8:748) in a PR merged an hour ago.

**Comment by aramase** [comment]
The release is complete, and the image is available now.

**Comment by chase-miller** [comment]
@aramase is it possible to adjust the release process to avoid this issue in the future?
