### ISSUE TITLE
Missing binaries for v1.4.0

### ISSUE THREAD

**Issue by tongpu** [Azure/azure-workload-identity#1515]
**Describe the bug**
Binaries for v1.4.0 are missing

**Steps To Reproduce**
```shell-session
# curl -I https://github.com/Azure/azure-workload-identity/releases/download/v1.4.0/azwi-v1.4.0-linux-amd64.tar.gz
HTTP/2 404
```

**Expected behavior**
Built binaries are available.

**Additional context**
Potentially caused by the release action failing: https://github.com/Azure/azure-workload-identity/actions/runs/12165808454/job/33930634489

**Comment by aramase** [comment]
Binaries have been uploaded to the release.
