### ISSUE TITLE
Is Workload Federated Identity works in Azure Machine Learning SDK V1

### ISSUE THREAD

**Issue by RajithaNelluru** [Azure/azure-workload-identity#1519]
When I try to autehnticate via Workload Federated Identity in Azure Machine Learning SDK V1- It is running more than 1 hour.
Logs:
DEBUG:azureml.core.authentication:'AZUREML_AAD_TOKEN_SECRET_NAME'
DEBUG:azureml._vendor.azure_cli_core:Current cloud config:
AzureCloud
DEBUG:azureml._vendor.azure_cli_core:Current cloud config:
AzureCloud
INFO:azureml._vendor.azure_cli_core._session:Failed to load or parse file C:\Users\VssAdministrator\.azureml\auth\azureProfile.json. It will be overridden by default settings.
INFO:azureml._vendor.azure_cli_core._session:Failed to load or parse file C:\Users\VssAdministrator\.azureml\auth\az.json. It will be overridden by default settings.
INFO:azureml._vendor.azure_cli_core._session:Failed to load or parse file C:\Users\VssAdministrator\.azureml\auth\az.sess. It will be overridden by default settings.
DEBUG:azureml._vendor.azure_cli_core:Current cloud config:
AzureCloud
DEBUG:urllib3.util.retry:Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG:msal.authority:Initializing with Entra authority: https://login.microsoftonline.com/organizations
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:[https://login.microsoftonline.com:443](https://login.microsoftonline.com/) "GET /organizations/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1589
DEBUG:msal.authority:openid_config("[https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration"](https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration%22)) = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': '[https://login.microsoftonline.com/{tenantid}/v2.0',](https://login.microsoftonline.com/%7Btenantid%7D/v2.0',) 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'http...
DEBUG:msal.application:Broker enabled? None
WARNING:azureml._vendor.azure_cli_core.auth.identity:The default web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
DEBUG:msal.telemetry:Generate or reuse correlation_id: 64793f4a-474b-4aff-9c2c-84319e1a8c42
DEBUG:msal.oauth2cli.oauth2:Using http://localhost:50861/ as redirect_uri
DEBUG:msal.oauth2cli.authcode:Abort by visit [http://localhost:50861?error=abort](http://localhost:50861/?error=abort)
INFO:msal.oauth2cli.authcode:Open a browser on this device to visit: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A50861&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2F.default+offline_access+openid+profile&state=ZbKBsHuvedExVmzP&code_challenge=O1mS-toHsfahthFfkJUAtesra_ihfxPcGypfR6W5610&code_challenge_method=S256&nonce=3f68546e76c2effc5cb5e5c73ca6c0700ddb72957d173fee3bea4db011c24768&client_info=1&prompt=select_account

**Comment by aramase** [comment]
@RajithaNelluru This would be a question for the Azure Machine Learning SDK team. Please open an issue in the corresponding SDK GitHub repo. This repo is for WI components that's deployed in the cluster (Mutating webhook).
