### ISSUE TITLE
CI: make release-manifest will overwrite latest version if a cherry pick patch is cut

### ISSUE THREAD

**Issue by sozercan** [Azure/azure-workload-identity#275]
**Describe the bug**

Cherry pick patch version will override the website version even if there is a newer minor version

https://github.com/Azure/azure-workload-identity/blob/main/Makefile#L400-L401

**Steps To Reproduce**

**Expected behavior**

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by chewong** [comment]
I don't think this will be an issue since cherry-pick PRs will be merged to release branches and our website only renders from the main branch.
