### ISSUE TITLE
azwi: Try to run create app results in segmentation violation in v0.7.0

### ISSUE THREAD

**Issue by pearj** [Azure/azure-workload-identity#352]
**Describe the bug**

Running `azwi serviceaccount create phase app --aad-application-name "${APPLICATION_NAME}"` results in a segmentation violation

**Steps To Reproduce**

Install azwi from [github release](https://github.com/Azure/azure-workload-identity/releases/download/v0.7.0/azwi-v0.7.0-linux-amd64.tar.gz)

Follow [step 4](https://azure.github.io/azure-workload-identity/docs/quick-start.html#4-create-an-aad-application-and-grant-permissions-to-access-the-secret) of the quick start

```
joelp@host:~$ azwi serviceaccount create phase app --aad-application-name "${APPLICATION_NAME}"
INFO[0000] No subscription provided, using selected subscription from Azure CLI: xxxx-xxxx-xxxx-xxxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4122770]

goroutine 1 [running]:
github.com/Azure/azure-workload-identity/pkg/cmd/serviceaccount/phases/create.(*aadApplicationPhase).run(0xc000707b68, {0x60eb9f0, 0xc000146048}, {0x5884640, 0xc000530820})
        /Users/ernestwong/go/src/github.com/Azure/azure-workload-identity/pkg/cmd/serviceaccount/phases/create/aadapplication.go:68 +0x190
github.com/Azure/azure-workload-identity/pkg/cmd/serviceaccount/phases/workflow.(*runner).Run(0xc00049d620, {0x5884640, 0xc000530820})
        /Users/ernestwong/go/src/github.com/Azure/azure-workload-identity/pkg/cmd/serviceaccount/phases/workflow/runner.go:124 +0x163
github.com/Azure/azure-workload-identity/pkg/cmd/serviceaccount/phases/workflow.(*runner).BindToCommand.func1(0xc0004c4f00, {0x5a3910a, 0x2, 0x2})
        /Users/ernestwong/go/src/github.com/Azure/azure-workload-identity/pkg/cmd/serviceaccount/phases/workflow/runner.go:90 +0xd0
github.com/spf13/cobra.(*Command).execute(0xc0004c4f00, {0xc0004309e0, 0x2, 0x2})
        /Users/ernestwong/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004c4280)
        /Users/ernestwong/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/ernestwong/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /Users/ernestwong/go/src/github.com/Azure/azure-workload-identity/cmd/azwi/main.go:15 +0x6f
```

**Expected behavior**

Command works properly

**Environment**

- Kubernetes version (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
  ```
  NAME="Ubuntu"
  VERSION="20.04.3 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.3 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal
  ```
- Kernel (e.g. `uname -a`): `Linux APEAC2VDD0009 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by chewong** [comment]
I wasn't able to repro this issue. What is the output of `az ad sp list --display-name "${AAD_APPLICATION_NAME}"`?

**Comment by chewong** [comment]
I do see we are dereferencing a pointer that can be potential nil. Let me open a PR to fix it.

**Comment by pearj** [comment]
It's an empty array `[]`, but that is expected right? Isn't `azwi serviceaccount create phase app` supposed to create the AAD application? Or is the order of step 4 wrong? Is the `az ad sp create-for-rbac --name "${APPLICATION_NAME}"` command supposed to be run first?

**Comment by pearj** [comment]
Ok so it turned out that it used a subscription I didn't expect and I don't have permissions on the subscription it tried.

I override the Azure config directory for the az cli with `AZURE_CONFIG_DIR`, but it seems like `azwi` ignores that.

So once I set the subscription as part of the command it no longer failed.

I guess azwi should probably handle permissions errors?

**Comment by chewong** [comment]
`azwi` is supposed to create the AAD application and we should definitely handle the permission issue. We recently switched to `github.com/microsoftgraph/msgraph-beta-sdk-go` as our core library for azwi and there might be somne unexpected response from the library that we didn't handle.
