### ISSUE TITLE
`azwi` CLI doesn't work inside Azure Cloud Shell

### ISSUE THREAD

**Issue by loekd** [Azure/azure-workload-identity#387]
**Describe the bug**
The `azwi` CLI does not currently work inside the Azure Cloud Shell
Commands like:
- `azwi serviceaccount create phase app --aad-application-name "${APPLICATION_NAME}"` 
- `azwi serviceaccount create phase sa`

fail with the same error message:
`Error: failed to run phase aad-application: failed to get AAD application: Azure CLI Credential: ERROR: Tenant shouldn't be specified for Cloud Shell account`

**Steps To Reproduce**
1. Open Azure Cloud Shell
2. Install `azw` 
  1. `wget https://github.com/Azure/azure-workload-identity/releases/download/v0.8.0/azwi-v0.8.0-linux-amd64.tar.gz` 
  2. `tar xvz -f azwi-v0.8.0-linux-amd64.tar.gz`
3. Run the provided commands, as part of the [quick start](https://azure.github.io/azure-workload-identity/docs/quick-start.html).

**Expected behavior**
The expected behavior is that the commands execute properly, when the tenantid matches the session's security context.

**Logs**
n/a
**Environment**
Azure Portal

- Kubernetes version (use `kubectl version`): 
  ```
   Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", 
   GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", 
   GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", 
   GitCommit:"299916054187763fc9be625667430fa45690357b", GitTreeState:"clean", BuildDate:"2022-01-30T03:25:00Z", 
   GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by chewong** [comment]
Thanks for reporting the bug. Feel free to follow the `azure-cli` route in the quick-start instead of `azwi` while we investigate this.
