### ISSUE TITLE
Quick Start issue - Add federated credential fails

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/azure-workload-identity#434]
**Describe the bug**

I'm following the quick start and hit an error when trying to add the federated identity credential:

```
~ az rest --method POST --uri "https://graph.microsoft.com/beta/applications/${APPLICATION_OBJECT_ID}/federatedIdentityCredentials" --body @body.json

Bad Request({"error":{"code":"InvalidFederatedIdentityCredentialValue","message":"The combination of issuer and subject must be unique for the application. Issuer https://oidc.prod-aks.azure.com/5b15da40-59ed-401c-b5f6-09ac41c12d7e/ and Subject: system:serviceaccount:default:workload-identity-sa already exist. paramName: FederatedIdentityCredential.Subject, paramValue: system:serviceaccount:default:workload-identity-sa, objectType: Microsoft.Online.DirectoryServices.Application","innerError":{"date":"2022-05-03T16:11:01","request-id":"4255561a-3c4b-4278-9115-acf7af7afd3b","client-request-id":"4255561a-3c4b-4278-9115-acf7af7afd3b"}}})
```

**Steps To Reproduce**

All steps were copied from https://azure.github.io/azure-workload-identity/docs/quick-start.html

I used an existing cluster and updated with `--enable-oidc-issuer` instead of creating a new cluster.  That's the only "gotcha" I see.

```
az aks update --resource-group ingress-pls --name ingress-pls --enable-oidc-issuer
az aks show --resource-group ingress-pls --name ingress-pls --query "oidcIssuerProfile.issuerUrl" -otsv
az keyvault create -g ingress-pls --name "${KEYVAULT_NAME}"
az keyvault secret set --vault-name "${KEYVAULT_NAME}" \\n   --name "${KEYVAULT_SECRET_NAME}" \\n   --value "Hello\!"
azwi serviceaccount create phase app --aad-application-name "${APPLICATION_NAME}"
export APPLICATION_CLIENT_ID="$(az ad sp list --display-name "${APPLICATION_NAME}" --query '[0].appId' -otsv)"
az keyvault set-policy --name "${KEYVAULT_NAME}" --secret-permissions get --spn "${APPLICATION_CLIENT_ID}"
azwi serviceaccount create phase sa --aad-application-name "${APPLICATION_NAME}" --service-account-namespace "${SERVICE_ACCOUNT_NAMESPACE}" --service-account-name "${SERVICE_ACCOUNT_NAME}"
azwi serviceaccount create phase federated-identity --aad-application-name "${APPLICATION_NAME}" --service-account-namespace "${SERVICE_ACCOUNT_NAMESPACE}" --service-account-name "${SERVICE_ACCOUNT_NAME}" --service-account-issuer-url "${SERVICE_ACCOUNT_ISSUER}"
export APPLICATION_OBJECT_ID="$(az ad app show --id ${APPLICATION_CLIENT_ID} --query objectId -otsv)"
cat <<EOF > body.json ...
az rest --method POST --uri "https://graph.microsoft.com/beta/applications/${APPLICATION_OBJECT_ID}/federatedIdentityCredentials" --body @body.json
```

**Expected behavior**

The `az rest` command would work successfully.

**Logs**

Let me know if there's any logs I should include.

**Environment**

- Kubernetes version (use `kubectl version`):
```
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"633e1432a197dc4a6a1807311429a9808b99ff5b", GitTreeState:"clean", BuildDate:"2022-03-30T18:27:54Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): OSX 12.3.1
- Kernel (e.g. `uname -a`): `Darwin Tommys-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64`
- Install tools:  `azure-cli                         2.34.1`
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Additional context**

**Comment by aramase** [comment]
> Bad Request({"error":{"code":"InvalidFederatedIdentityCredentialValue","message":"The combination of issuer and subject must be unique for the application. Issuer https://oidc.prod-aks.azure.com/5b15da40-59ed-401c-b5f6-09ac41c12d7e/ and Subject: system:serviceaccount:default:workload-identity-sa already exist. paramName: FederatedIdentityCredential.Subject, paramValue: system:serviceaccount:default:workload-identity-sa, objectType: Microsoft.Online.DirectoryServices.Application","innerError":{"date":"2022-05-03T16:11:01","request-id":"4255561a-3c4b-4278-9115-acf7af7afd3b","client-request-id":"4255561a-3c4b-4278-9115-acf7af7afd3b"}}})

@lastcoolnameleft this error indicates you have already have a federated identity credential configured for the app with `issuer: https://oidc.prod-aks.azure.com/5b15da40-59ed-401c-b5f6-09ac41c12d7e/` and `subject: system:serviceaccount:default:workload-identity-sa`. You don't need to run `az rest` again to add it as it already exists.

From the list of commands you posted, I see you're running 
```bash
azwi serviceaccount create phase federated-identity --aad-application-name "${APPLICATION_NAME}" --service-account-namespace "${SERVICE_ACCOUNT_NAMESPACE}" --service-account-name "${SERVICE_ACCOUNT_NAME}" --service-account-issuer-url "${SERVICE_ACCOUNT_ISSUER}"
```
and 
```bash
az rest --method POST --uri "https://graph.microsoft.com/beta/applications/${APPLICATION_OBJECT_ID}/federatedIdentityCredentials" --body @body.json
```

You only need to run `azwi serviceaccount create phase federated-identity` or `az rest --method POST` to establish trust and not both. `azwi serviceaccount create phase federated-identity` command already setup the trust and `az rest` to do the same is failing because the trust has already been established.

**Comment by lastcoolnameleft** [comment]
Oh!  If I understand correctly, the steps for using "Azure Workload Identity CLI" and "kubectl" and "Az CLI" are mutually exclusive.  (i.e. either run the Azure Workload Identity CLI OR az CLI). Not both, sequentially, right?

**Comment by aramase** [comment]
> Oh! If I understand correctly, the steps for using "Azure Workload Identity CLI" and "kubectl" and "Az CLI" are mutually exclusive. (i.e. either run the Azure Workload Identity CLI OR az CLI). Not both, sequentially, right?

Correct! `azwi` is a tool we have developed as part of this project to automate some of the steps. If you don't want to use `azwi`, then you can run the commands provided with `azure-cli` and `kubectl` for each step.

**Comment by aramase** [comment]
@lastcoolnameleft Were you able to get the quick start working?

**Comment by lastcoolnameleft** [comment]
Yes, now that I understood that the instructions were mutually exclusive, I was able to get it all working.  Thanks!  Closing.
