### ISSUE TITLE
.Net Azure.Identity -> DefaultAzureCredential() fails

### ISSUE THREAD

**Issue by mnj** [Azure/azure-workload-identity#440]
**Describe the bug**
This does not seem to work with the .NET Azure.Identity packages, which new asp.net core 6, projects seem to prefer using these days.

**Steps To Reproduce**
DefaultAzureCredential() tries many different ways to authenticate to keyvault/azure sql, but none of them works with the token file azure-workload-identity uses.

**Expected behavior**
That authentication to various azure services would just work.

**Environment**

- Kubernetes version : v1.23.5
- Cloud provider or hardware configuration: Azure AKS
- Plain new .NET Core 6 project, using Azure.Identity

**Additional context**
There is a similar issue on:
https://github.com/Azure/azure-sdk-for-net/issues/27159

Which doesn't seem to get much work/focus.

**Comment by aramase** [comment]
@mnj https://github.com/Azure/azure-sdk-for-net/issues is the right place for this and looks like you already have an issue created there.

@schaabs @chlowell could you help with this?

**Comment by aramase** [comment]
This is a SDK issue, so closing this one. This should be tracked by the sdk team in https://github.com/Azure/azure-sdk-for-net/issues/27159
