### ISSUE TITLE
Make the failurePolicy of the mutating admission controller configurable

### ISSUE THREAD

**Issue by tkent** [Azure/azure-workload-identity#516]
**Is your feature request related to a problem? Please describe.**

The helm chart [does not allow the `failurePolicy` for the mutating admission controller to be configurable](https://github.com/Azure/azure-workload-identity/blob/8644a217f09902fa1ac63e05cf04d9a3f3f1ebc3/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml#L20). Since pods can be created or updated before the Azure Workload Identity webhook controllers have started up, they can be correctly annotated but fail to have the credential information injected into their definition. 

**Describe the solution you'd like**

Allow the user to specify what type of `failurePolicy` they'd like to have in their cluster. 

**Describe alternatives you've considered**

n/a

**Additional context**

This comes in scenarios where many nodes are being swapped - especially in small clusters.

**Comment by sozercan** [comment]
@tkent Gatekeeper has some considerations documented here https://open-policy-agent.github.io/gatekeeper/website/docs/failing-closed, this is especially important since you are swapping nodes. Fail closed can cause circular dependencies in your clusters.

**Comment by tkent** [comment]
Thanks @aramase!

@sozercan  - I appreciate the warning. Hopefully, in a future version of k8s, we'll be able to define scope rules that exclude the pods providing the webhook to avoid the chicken-and-egg problem [kubernetes#92157](https://github.com/kubernetes/kubernetes/issues/92157).
