### ISSUE TITLE
Support for "az login --identity"

### ISSUE THREAD

**Issue by sukumarpatel** [Azure/azure-workload-identity#521]
**Is your feature request related to a problem? Please describe.**
Does this project support "az login --identity" from within a pod with az cli installed?

**Describe the solution you'd like**
az login --identity should work

**Describe alternatives you've considered**
What are the alternates to the above command? How can we login using azcli and workload identity

**Additional context**
We have many shell scripts which use azcli to perform an authentication. I wanted to check if workload identiy supports it or is planned in the future.

**Comment by aramase** [comment]
@sukumarpatel Workload identity federation (WIF) support for managed identity is in progress. If you're using WIF with Azure AD Apps and the webhook from this repo, then you can use `az login` with the federated service account token and the env vars injected by the webhook

```bash
az login --service-principal -u 'echo $AZURE_CLIENT_ID' -t 'echo $AZURE_TENANT_ID' --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE) --allow-no-subscriptions
```

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/azure-workload-identity/issues/521#issuecomment-1215344696. Feel free to reopen if you have any questions.

**Comment by dbg-raghulkrishna** [comment]
now that workload identity supports MSI is az login --identity possible?

**Comment by dbg-raghulkrishna** [comment]
@aramase  
now that workload identity supports user assigned identity is az login --identity possible?
