### ISSUE TITLE
Environment variables not injected into the pod

### ISSUE THREAD

**Issue by mich1990** [Azure/azure-workload-identity#525]
**Describe the bug**

Environment variables not injected into the pod, service account is correctly annotated with client-id and label to use workload identities set to true (same settings work on other pods in different namespace).

Tried deleting the pod, deployment and service account. The app is deployed to the kube-system namespace, so wondering if there is exclusion on this namespace for webhook injections?

**Steps To Reproduce**

**Expected behavior**

Environment variables and volume with a path to token should be created.

- Kubernetes version (use `kubectl version`): 1.22.11 AKS
- Cloud provider or hardware configuration: AZURE

**Comment by aramase** [comment]
> Tried deleting the pod, deployment and service account. The app is deployed to the kube-system namespace, so wondering if there is exclusion on this namespace for webhook injections?

There are no exclusions configured for a specific namespace. Could you share the output for `kubectl get serviceaccount <name> -o yaml` and `kubectl get pod <name> -o yaml`?

**Comment by mich1990** [comment]
Pod (its going into crash loop after about 30 seconds but I dont think it should make a difference?)

`apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-08-15T07:48:48Z"
  generateName: external-dns-8d895fdd8-
  labels:
    aadpodidbinding: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    pod-template-hash: 8d895fdd8
  name: external-dns-8d895fdd8-tr62m
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: external-dns-8d895fdd8
    uid: 693a434e-646a-45b8-a228-fd1cd6b044b5
  resourceVersion: "4790008"
  uid: 44c7df95-a118-4213-8488-4e792b198c58
spec:
  containers:
  - args:
    - --source=service
    - --source=ingress
    - --domain-filter=dev.adept-devops.eu.wejo.io
    - --provider=azure
    - --policy=upsert-only
    env:
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value: aks-eu-adept-devops-dev-green-.hcp.northeurope.azmk8s.io
    - name: KUBERNETES_PORT
      value: tcp://aks-eu-adept-devops-dev-green-.hcp.northeurope.azmk8s.io:443
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://aks-eu-adept-devops-dev-green-.hcp.northeurope.azmk8s.io:443
    - name: KUBERNETES_SERVICE_HOST
      value: aks-eu-adept-devops-dev-green-.hcp.northeurope.azmk8s.io
    image: k8s.gcr.io/external-dns/external-dns:v0.9.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: external-dns
    ports:
    - containerPort: 7979
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 6
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: azure-config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rgml5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-defaultpool-
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
  serviceAccount: external-dns
  serviceAccountName: external-dns
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: azure.json
        path: azure.json
      name: azure-config
    name: azure-config
  - name: kube-api-access-rgml5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-08-15T07:48:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-08-15T07:48:48Z"
    message: 'containers with unready status: [external-dns]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-08-15T07:48:48Z"
    message: 'containers with unready status: [external-dns]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-08-15T07:48:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2163cedbeafb88c8231b35618d1643c711404d1894563e51080d3460dc581868
    image: k8s.gcr.io/external-dns/external-dns:v0.9.0
    imageID: k8s.gcr.io/external-dns/external-dns@sha256:78c0331e57f0d9fb2c0ba108d89334cc0b616843b675eaccafc85719b37e225b
    lastState: {}
    name: external-dns
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-08-15T07:48:49Z"
  hostIP: 10.11.64.4
  phase: Running
  podIP: 10.11.64.27
  podIPs:
  - ip: 10.11.64.27
  qosClass: BestEffort
  startTime: "2022-08-15T07:48:48Z"
`

Service Account (please note I have deleted some parts of my client id

`apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: -0175-4c52-86f8-
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"azure.workload.identity/client-id":"-0175-4c52-86f8-"},"labels":{"app.kubernetes.io/instance":"external-dns","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"external-dns","app.kubernetes.io/version":"0.9.0","azure.workload.identity/use":"true","helm.sh/chart":"external-dns-1.2.0","k8s.wejo.io/appname":"devops-dev-external-dns-green"},"name":"external-dns","namespace":"kube-system"}}
  creationTimestamp: '2022-08-12T08:30:14Z'
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.9.0
    azure.workload.identity/use: 'true'
    helm.sh/chart: external-dns-1.2.0
    k8s.wejo.io/appname: devops-dev-external-dns-green
  name: external-dns
  namespace: kube-system
  resourceVersion: '3550233'
  uid: 128daab5-5b2b-4226-8f37-341ff9c8adbb
secrets:
  - name: external-dns-token-s7fqb`

**Comment by aramase** [comment]
Thanks for the yamls! Could you share the following:
1. output for `kubectl get pods -n <namespace where workload identity webhook is installed -o yaml`
2. logs from the webhook pods?
3. `kubectl get mutatingwebhookconfiguration -n <webhook namespace> azure-wi-webhook-mutating-webhook-configuration -o yaml`

**Comment by mich1990** [comment]
Pod YAML (its running fine BTW)

`apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2022-08-11T14:26:43Z"
    generateName: azure-wi-webhook-controller-manager-857b977844-
    labels:
      app: workload-identity-webhook
      azure-workload-identity.io/system: "true"
      chart: workload-identity-webhook
      pod-template-hash: 857b977844
      release: azure-workload-identity
    name: azure-wi-webhook-controller-manager-857b977844-ds944
    namespace: azure-workload-identity-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: azure-wi-webhook-controller-manager-857b977844
      uid: c00a4eb4-03dc-4c2f-a60e-dfbf06dde297
    resourceVersion: "3236320"
    uid: a2bdd7f1-3c0a-4316-8f06-f91b20f78299
  spec:
    affinity: {}
    containers:
    - args:
      - --arc-cluster=false
      - --log-encoder=console
      - --metrics-addr=:8095
      - --metrics-backend=prometheus
      command:
      - /manager
      env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      envFrom:
      - configMapRef:
          name: azure-wi-webhook-config
      image: mcr.microsoft.com/oss/azure/workload-identity/webhook:v0.12.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: healthz
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: manager
      ports:
      - containerPort: 8095
        name: metrics
        protocol: TCP
      - containerPort: 9443
        name: webhook-server
        protocol: TCP
      - containerPort: 9440
        name: healthz
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /readyz
          port: healthz
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 100m
          memory: 30Mi
        requests:
          cpu: 100m
          memory: 20Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /certs
        name: cert
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-wttzq
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: aks-defaultpool-11546069-vmss000000
    nodeSelector:
      kubernetes.io/os: linux
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: azure-wi-webhook-admin
    serviceAccountName: azure-wi-webhook-admin
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    volumes:
    - name: cert
      secret:
        defaultMode: 420
        secretName: azure-wi-webhook-server-cert
    - name: kube-api-access-wttzq
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:43Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:45Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:45Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:43Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://341847b3e24a4da70c72eaf327d604052602a77ce1bb0dece294224ba180e132
      image: mcr.microsoft.com/oss/azure/workload-identity/webhook:v0.12.0
      imageID: mcr.microsoft.com/oss/azure/workload-identity/webhook@sha256:e191b09b1d253378975d796a4315a8992437970f39f962c2b43fd7f53b2a1e2a
      lastState: {}
      name: manager
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-08-11T14:26:44Z"
    hostIP: 10.11.64.4
    phase: Running
    podIP: 10.11.64.10
    podIPs:
    - ip: 10.11.64.10
    qosClass: Burstable
    startTime: "2022-08-11T14:26:43Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2022-08-11T14:26:34Z"
    generateName: azure-wi-webhook-controller-manager-857b977844-
    labels:
      app: workload-identity-webhook
      azure-workload-identity.io/system: "true"
      chart: workload-identity-webhook
      pod-template-hash: 857b977844
      release: azure-workload-identity
    name: azure-wi-webhook-controller-manager-857b977844-kbx2v
    namespace: azure-workload-identity-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: azure-wi-webhook-controller-manager-857b977844
      uid: c00a4eb4-03dc-4c2f-a60e-dfbf06dde297
    resourceVersion: "3236250"
    uid: 814594ff-2f49-4585-9ca2-30b2c9974fb3
  spec:
    affinity: {}
    containers:
    - args:
      - --arc-cluster=false
      - --log-encoder=console
      - --metrics-addr=:8095
      - --metrics-backend=prometheus
      command:
      - /manager
      env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      envFrom:
      - configMapRef:
          name: azure-wi-webhook-config
      image: mcr.microsoft.com/oss/azure/workload-identity/webhook:v0.12.0
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: healthz
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: manager
      ports:
      - containerPort: 8095
        name: metrics
        protocol: TCP
      - containerPort: 9443
        name: webhook-server
        protocol: TCP
      - containerPort: 9440
        name: healthz
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /readyz
          port: healthz
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 100m
          memory: 30Mi
        requests:
          cpu: 100m
          memory: 20Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /certs
        name: cert
        readOnly: true
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rp69l
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: aks-defaultpool-11546069-vmss000002
    nodeSelector:
      kubernetes.io/os: linux
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: azure-wi-webhook-admin
    serviceAccountName: azure-wi-webhook-admin
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    volumes:
    - name: cert
      secret:
        defaultMode: 420
        secretName: azure-wi-webhook-server-cert
    - name: kube-api-access-rp69l
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:34Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:37Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:37Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2022-08-11T14:26:34Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://1754dc8361ef7ae0b24ca254fb42dcc79f3a13a3a3a1f3d9c7c495b8590d54af
      image: mcr.microsoft.com/oss/azure/workload-identity/webhook:v0.12.0
      imageID: mcr.microsoft.com/oss/azure/workload-identity/webhook@sha256:e191b09b1d253378975d796a4315a8992437970f39f962c2b43fd7f53b2a1e2a
      lastState: {}
      name: manager
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2022-08-11T14:26:35Z"
    hostIP: 10.11.64.34
    phase: Running
    podIP: 10.11.64.60
    podIPs:
    - ip: 10.11.64.60
    qosClass: Burstable
    startTime: "2022-08-11T14:26:34Z"
kind: List
metadata:
  resourceVersion: ""`
  
  Logs from one of the pods
  
  I0811 14:26:36.094500       1 logr.go:261] entrypoint "msg"="initializing metrics backend"  "backend"="prometheus"
I0811 14:26:36.094589       1 logr.go:261] entrypoint "msg"="setting up manager"  "userAgent"="azure-workload-identity/webhook/v0.12.0 (linux/amd64) 8644a21/2022-07-26-22:19"
I0811 14:26:37.222788       1 logr.go:261] controller-runtime/metrics "msg"="Metrics server is starting to listen"  "addr"=":8095"
I0811 14:26:37.223469       1 logr.go:261] entrypoint "msg"="setting up cert rotation"  
I0811 14:26:37.223906       1 logr.go:261] entrypoint "msg"="starting manager"  
I0811 14:26:37.224352       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":8095,"Zone":""} "kind"="metrics" "path"="/metrics" 
I0811 14:26:37.224451       1 internal.go:362]  "msg"="Starting server" "addr"={"IP":"::","Port":9440,"Zone":""} "kind"="health probe" 
I0811 14:26:37.224531       1 logr.go:261] cert-rotation "msg"="starting cert rotator controller"  
I0811 14:26:37.224692       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*v1.Secret=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} <nil> map[] map[] }) %!s(*cache.informerCache=&{0xc000049040}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I0811 14:26:37.224736       1 controller.go:185]  "msg"="Starting EventSource" "controller"="cert-rotator" "source"="&{{%!s(*unstructured.Unstructured=&{map[apiVersion:admissionregistration.k8s.io/v1 kind:MutatingWebhookConfiguration]}) %!s(*cache.informerCache=&{0xc000049040}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"
I0811 14:26:37.224758       1 controller.go:193]  "msg"="Starting Controller" "controller"="cert-rotator" 
I0811 14:26:37.326431       1 controller.go:227]  "msg"="Starting workers" "controller"="cert-rotator" "worker count"=1
I0811 14:26:37.326956       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0811 14:26:37.327021       1 logr.go:261] cert-rotation "msg"="certs are ready in /certs"  
I0811 14:26:37.327490       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0811 14:26:39.234982       1 logr.go:261] cert-rotation "msg"="CA certs are injected to webhooks"  
I0811 14:26:39.235031       1 logr.go:261] entrypoint "msg"="setting up webhook server"  
I0811 14:26:39.235105       1 logr.go:261] entrypoint "msg"="registering webhook to the webhook server"  
I0811 14:26:39.235290       1 server.go:216] controller-runtime/webhook/webhooks "msg"="Starting webhook server"  
I0811 14:26:39.235292       1 server.go:148] controller-runtime/webhook "msg"="Registering webhook" "path"="/mutate-v1-pod" 
I0811 14:26:39.235530       1 logr.go:261] controller-runtime/certwatcher "msg"="Updated current TLS certificate"  
I0811 14:26:39.235686       1 logr.go:261] controller-runtime/webhook "msg"="Serving webhook server"  "host"="" "port"=9443
I0811 14:26:39.235822       1 logr.go:261] controller-runtime/certwatcher "msg"="Starting certificate watcher"  
I0812 02:26:37.328147       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0812 07:04:27.906785       1 webhook.go:122] handler "msg"="service account not annotated" "namespace"="adept" "pod"="adept-ingress-zookeeper-0" "service-account"="adept-ingress-zookeeper" 
I0812 11:33:08.639550       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0812 12:05:22.230556       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0812 14:26:37.328796       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0812 22:06:24.344320       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0812 22:54:44.731073       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0813 02:26:37.328255       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0813 08:39:40.049133       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0813 09:44:07.232058       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0813 11:51:16.105316       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0813 11:51:16.664585       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0813 14:26:37.327809       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0813 22:24:32.369440       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0813 22:40:38.606316       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0814 02:26:37.328321       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0814 08:57:48.074380       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0814 09:30:01.107440       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0814 14:26:37.328290       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0814 19:31:03.778817       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0814 20:19:23.608428       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0815 02:26:37.328164       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0815 06:04:19.483880       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0815 07:08:46.108888       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0815 14:26:37.328460       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0815 16:37:35.188512       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0815 17:58:08.609125       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0816 02:26:37.328447       1 logr.go:261] cert-rotation "msg"="no cert refresh needed"  
I0816 03:10:50.893190       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"
I0816 04:47:31.110217       1 rotator.go:685] cert-rotation "msg"="Ensuring CA cert"  "gvk"={"Group":"admissionregistration.k8s.io","Version":"v1","Kind":"MutatingWebhookConfiguration"} "name"="azure-wi-webhook-mutating-webhook-configuration"


Configuration (please note I ahve deleted a large part of the caBundle

`apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: azure-workload-identity
    meta.helm.sh/release-namespace: azure-workload-identity-system
  creationTimestamp: "2022-08-11T10:09:02Z"
  generation: 3
  labels:
    app: workload-identity-webhook
    app.kubernetes.io/managed-by: Helm
    azure-workload-identity.io/system: "true"
    chart: workload-identity-webhook
    release: azure-workload-identity
  name: azure-wi-webhook-mutating-webhook-configuration
  resourceVersion: "3164551"
  uid: b915771d-1853-4d36-8352-02706b2d2a0e
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjakNDQWxxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREJITVNBd0hnWURWUVFLRXhkaGVuVnkKWlMxM2IzSnJiRzloWkMxcFpHVnVkR2wwZVRFak1DRUdBMVVFQXhNYVlYcDFjbVV0ZDI5eWEyeHZZV1F0YVdSbApiblJwZEhrdFkyRXdIaGNOTWpJd09ERXhNRGt3T1RBMVdoY05Nekl3T0RBNE1UQXdPVEExV2pCSE1TQXdIZ1lEClZRUUtFeGRoZW5WeVpTMTNiM0pyYkc5aFpDMXBaR1Z1ZEdsMGVURWpNQ0VHQTFVRUF4TWFZ
    service:
      name: azure-wi-webhook-webhook-service
      namespace: azure-workload-identity-system
      path: /mutate-v1-pod
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: mutation.azure-workload-identity.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10`

**Comment by hamza-tumturk** [comment]
@aramase The issue seems to be caused by the buildin Azure AKS [Admissions Enforcer](https://docs.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces).
The unwanted `namespaceSelector` gets injected by that.

**Comment by mich1990** [comment]
@aramase thats a great spot, I wasn't looking for it as I didn't expect it there. @hamza-tumturk thank you for your suggestion! A solution can be found here: [https://github.com/kubeflow/pipelines/issues/5244#issuecomment-961666694](url) and it works I can confirm that once the annotation is added the envs variables are injected.

@aramase Since this is very likely to happen to more people and we dont exclude namespaces shall I create a Pull Request with the annotation added to the [https://github.com/Azure/azure-workload-identity/blob/main/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml](url)

**Comment by aramase** [comment]
> @aramase Since this is very likely to happen to more people and we dont exclude namespaces shall I create a Pull Request with the annotation added to the [https://github.com/Azure/azure-workload-identity/blob/main/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml](https://github.com/Azure/azure-workload-identity/issues/url)

@mich1990 The webhook can be deployed in non-AKS clusters and this annotation is specific to AKS, I would prefer we start with adding this to the documentation here: https://azure.github.io/azure-workload-identity/docs/known-issues.html. If we get more requests for adding this label by default in the future, we can consider adding it. Would you be interested in opening a PR to add to the docs [here](https://github.com/Azure/azure-workload-identity/blob/main/docs/book/src/known-issues.md)?

**Comment by mich1990** [comment]
@aramase done

**Comment by mich1990** [comment]
@aramase is it worth adding functionality to the values.yaml file so that we can add the annotation? like its currently done for the labels

**Comment by aramase** [comment]
> @aramase is it worth adding functionality to the values.yaml file so that we can add the annotation? like its currently done for the labels

That makes sense. I'll open a PR to make that configurable.
