### ISSUE TITLE
Pod with workload identity not functioning when webhook has no replicas

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-workload-identity#540]
**Describe the bug**
If there is a node state change, it is possible that webhook active replicas become 0
pod created during this period will skip webhook that would not function with workload identity.

**Steps To Reproduce**
Scale down webhook replica to 0
Create a new pod with workload identity func.

**Expected behavior**
New created pod work with workload identity

**Additional context**
The cause is:
1. mutating webhook policy is set to [ignore](https://github.com/Azure/azure-workload-identity/blob/main/deploy/azure-wi-webhook.yaml#L222)
2. No PodDisruptionBudget specified
3. replicas is set 2

Solutions to discuss
From pod identity side, can enforce policy/add pdb/increase replica?
From user pod side, can add a condition that if workload identity env is not detected, the pod should terminate and restart?

**Comment by chkohner** [comment]
Similarly, if bootstrapping a cluster (for instance using terraform), there is a race condition when installing AZWI along with application(s) that require it. It's unclear what the best programmatic way to defer application pod creation is or what readiness checks are available to ensure AZWI will correctly inject things.

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/azure-workload-identity/releases/tag/v1.0.0-alpha.0 release.
