### ISSUE TITLE
`v0.13.0` release is in progress, use `v0.12.0` release

### ISSUE THREAD

**Issue by aramase** [Azure/azure-workload-identity#546]
The latest release `v0.13.0` is in progress and the image is not yet available. For installation, please use `v0.12.0` release and helm chart version `0.12.0` until this issue is closed.

**Comment by Ishani-Gupta** [comment]
@aramase  Can you point me to how to use v0.12.0 with helm? I am using below commands as mentioned in [this workbook](https://azure.github.io/azure-workload-identity/docs/installation/mutating-admission-webhook.html)

```
helm repo add azure-workload-identity https://azure.github.io/azure-workload-identity/charts
helm repo update
helm install workload-identity-webhook azure-workload-identity/workload-identity-webhook \
   --namespace azure-workload-identity-system \
   --create-namespace \
   --set azureTenantID="${AZURE_TENANT_ID}"
```
