### ISSUE TITLE
Using `azcopy` from an init-container with Workload Identity

### ISSUE THREAD

**Issue by adam-orosz** [Azure/azure-workload-identity#556]
**Is your feature request related to a problem? Please describe.**
We need to use Go binaries e.g [azcopy](https://github.com/Azure/azure-storage-azcopy) in init-containers in pods that utilise Workload Identity. While the binaries function normally in non-init containers, they fail to get tokens in init-containers.

e.g. `azcopy` produces the following output in an init-container in a pod that uses Workload Identity:

`Failed to perform login command:`
`failed to get token from msi, status code: 400`

**Describe the solution you'd like**
How can we use Workload Identity e.g [azcopy](https://github.com/Azure/azure-storage-azcopy) without needing to inject and rely on the proxy container?

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
> How can we use Workload Identity e.g [azcopy](https://github.com/Azure/azure-storage-azcopy) without needing to inject and rely on the proxy container?

For this, `azcopy` would need to use the latest SDK to support workload identity.

**Comment by adam-orosz** [comment]
> > How can we use Workload Identity e.g [azcopy](https://github.com/Azure/azure-storage-azcopy) without needing to inject and rely on the proxy container?
> 
> For this, `azcopy` would need to use the latest SDK to support workload identity.

Thanks for the response! Could you provide a link to the SKD (version) that is the minimum supported version? Is it the MSAL for Go SDK?

**Comment by aramase** [comment]
> > > How can we use Workload Identity e.g [azcopy](https://github.com/Azure/azure-storage-azcopy) without needing to inject and rely on the proxy container?
> > 
> > 
> > For this, `azcopy` would need to use the latest SDK to support workload identity.
> 
> Thanks for the response! Could you provide a link to the SKD (version) that is the minimum supported version? Is it the MSAL for Go SDK?

If `azcopy` is using AzureIdentity SDK, then minimum versions are here: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html. If they're using ADAL, then it would be recommended to move to AzureIdentity SDK or MSAL.

**Comment by aramase** [comment]
Closing this in favor of https://github.com/Azure/azure-storage-azcopy/issues/1907
