### ISSUE TITLE
Evaluate using `distroless-iptables` base image for proxy-init

### ISSUE THREAD

**Issue by aramase** [Azure/azure-workload-identity#564]
ref: https://console.cloud.google.com/gcr/images/k8s-staging-build-image/global/distroless-iptables

**Comment by sozercan** [comment]
Investigate https://github.com/project-copacetic/copacetic to patch

cc @codemonkeyleet @ashnamehrotra @pmengelbert

**Comment by sozercan** [comment]
ref https://github.com/kubernetes/release/pull/2502
