### ISSUE TITLE
Share user's login so that container on non-azure vm can run in the context of the user's environment

### ISSUE THREAD

**Issue by anthonsu** [Azure/azure-workload-identity#582]
**Is your feature request related to a problem? Please describe.**
Today our team is using KinD cluster on local machine (non-Azure VM) to bootstrap cluster api for azure (capz) worker cluster that runs in Azure and later run our own service cluster on top of that capz cluster.
Since KinD cluster is not in Azure environment, User Managed Identity (MSI) cannot be bound with it. Therefore we have to use alternative identity. User's login identity is an ideal option because we already run `az` command there on local machine. But this is not supported today. 

As cluster api for azure (capz) requires an existing cluster environment to bootstrap the actual worker cluster and KinD is a pretty light weight approach to run on user's local environment (comparing with a full AKS cluster), this should be a very common and high demand feature request.

**Describe the solution you'd like**
Share the rights from the user's login to container that runs on non-Azure machine so that container can run commands in the context of the user's environment so that local cluster (i.e. KinD) can use user's login to bootstrap capz worker cluster in Azure.

**Describe alternatives you've considered**
As explained above, an AKS cluster can be such bootstrap cluster, but this is sometimes too heavy and time consuming by comparing with a KinD cluster on local.

Another workaround is to bootstap via a VM in Azure running Docker/KinD inside. But again, it is a waste that to create an Azure VM is only to make User Managed Identity be able to bind with KinD.

**Comment by aramase** [comment]
> Share the rights from the user's login to container that runs on non-Azure machine so that container can run commands in the context of the user's environment so that local cluster (i.e. KinD) can use user's login to bootstrap capz worker cluster in Azure.

@anthonsu Workload identity is based on OIDC federation and with this you don't need the managed identity to be assigned to the VM/VMSS. This means workload identity will work in any cloud or on-premises cluster. Try out the [quick start](https://azure.github.io/azure-workload-identity/docs/quick-start.html) with managed identity to learn more how this can be done.

For CAPZ, the CAPZ project is looking at supporting workload identity with managed identity. xref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2205. (cc @CecileRobertMichon)

**Comment by aramase** [comment]
Closing this issue as it's not a feature for workload identity. Feel free to open a new issue if you have any additional questions or feedback.
