### ISSUE TITLE
Support for private AKS clusters

### ISSUE THREAD

**Issue by chandlerkent** [Azure/azure-workload-identity#584]
We have been evaluating workload identities for our AKS cluster since the beginning of the public preview awaiting it to go generally available. With the addition of support for user-assigned managed identities (very important for our use case!), we are taking another look at this feature.

It appears the OIDC provider likely has to public so that Azure AD can access the endpoints to validate the token and exchange for an AAD token. Is that correct? If so, how would this work in an AKS cluster which has no public internet presence?

Thank you!

**Comment by aramase** [comment]
@miwithro @karataliu Could you provide details on this?

**Comment by chandlerkent** [comment]
@miwithro thank you for confirming. Is this public endpoint something hosted in the AKS cluster or hosted by Azure somewhere behind the scenes?

**Comment by miwithro** [comment]
hosted by Azure behind the scenes.

**Comment by chandlerkent** [comment]
@miwithro great, thanks for all the help!
