### ISSUE TITLE
Pods should opt-in to webhook mutation directly

### ISSUE THREAD

**Issue by enj** [Azure/azure-workload-identity#601]
**Is your feature request related to a problem? Please describe.**

Today, the default configuration of the webhook is to intercept all pod mutations:

https://github.com/Azure/azure-workload-identity/blob/6c77e4071a7c6cbd08d16e0c128a25972a7b3ce8/charts/workload-identity-webhook/templates/azure-wi-webhook-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml#L21-L34

and the default `mutatingWebhookObjectSelector` is empty:

https://github.com/Azure/azure-workload-identity/blob/6c77e4071a7c6cbd08d16e0c128a25972a7b3ce8/charts/workload-identity-webhook/README.md?plain=1#L55

The webhook uses the service account associated with the pod to filter the mutation logic:

https://github.com/Azure/azure-workload-identity/blob/6c77e4071a7c6cbd08d16e0c128a25972a7b3ce8/pkg/webhook/webhook.go#L120-L124

While a user could specify a custom `mutatingWebhookObjectSelector` and `mutatingWebhookFailurePolicy`, I believe we can have better defaults around this flow.  The webhook should only be invoked if we actually expect to mutate the pod.  This will reduce the latency impact of the webhook and allow us to fail closed (not as a security boundary, but instead to prevent pods from starting in an unexpected state).

**Describe the solution you'd like**

The defaults should be changed so that:

`objectSelector` `->` `azure.workload.identity/use`

https://github.com/Azure/azure-workload-identity/blob/6c77e4071a7c6cbd08d16e0c128a25972a7b3ce8/pkg/webhook/consts.go#L6

`failurePolicy` `->` `Fail`

The webhook would be updated to mutate the pod if either pod or the service account has the label (eventually these checks will be removed altogether and the webhook would always mutate the pod).

To limit the impact of this breaking change, we could do a few things:

- Attempt to issue warnings and audit annotations to help users know that this change is coming
- Template the `mutatingWebhookObjectSelector` YAML so that it can be set to the empty string as a way to restore the old behavior for a period of time
- Have the change behind a feature gate for some period of time (and the gate's default state would change from off to on over time)

**Describe alternatives you've considered**

Not sure what other options there are.

**Additional context**

xref #540

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/azure-workload-identity/releases/tag/v1.0.0-alpha.0 release.
