### ISSUE TITLE
 The feature 'EnableOIDCIssuerPreview' could not be found.

### ISSUE THREAD

**Issue by tshaiman** [Azure/azure-workload-identity#609]
**Describe the bug**
Trying to register the EnableOIDCIssuerPreview on a GovCloud Cluster fails.
as far as I understand Workload Identity is in GA already which raises two concerns : 
- why do we still need to register OIDCIssuerPreview plugin
- whether this is supported on AuzreUsGovernment
**Steps To Reproduce**
0. follow this tutorial : [Azure Docs](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster#register-the-enableworkloadidentitypreview-feature-flag) 
1. login to AzureUsGovernment based subscription
2. ensure your CLI = 2.41.0 (latest)
3. run : 
```
 az feature register --namespace "Microsoft.ContainerService" --name "EnableOIDCIssuerPreview"
```
you will get : Message: The feature 'EnableOIDCIssuerPreview' could not be found.

**Expected behavior**
1. enabling EnableWorkloadIdentityPreview should not be in Preview as WIF is in GA
2. enabling OIDCIssuer should not be considered as Preview Feature once WIF is in GA
3. Registration should succeed on all clouds.  
**Logs**

**Environment**
- USGovCloud Subscription
- Az CLI : 2.41.0
- kubectl version 1.24
- AKS Cluster version 1.24.6
- AKS Network : Kubenet

**Additional context**

**Comment by sozercan** [comment]
@tshaiman it might be better to open this issue on https://github.com/azure/aks

**Comment by tshaiman** [comment]
moving to AKS Team
