### ISSUE TITLE
AAD not issuing token again api-server generated token

### ISSUE THREAD

**Issue by mslearner** [Azure/azure-workload-identity#616]
**Describe the bug**

The API servver sends the token to AAD but AAD is rejecting it. API server needs to get an AAD token

**Steps To Reproduce**

Run the tutorial in the quickstart

**Expected behavior**

**Logs**

E1027 23:39:22.893319       1 token_credential.go:62] "failed to acquire token" err="FromAssertion(): http call(https://login.microsoftonline.com/78f9c33e-5b36-4730-93a8-9416d43ee1b3/oauth2/v2.0/token)(POST) error: reply status code was 400:\n{\"error\":\"invalid_request\",\"error_description\":\"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://kubernetes.default.svc.cluster.local'. Assertion Subject: 'system:serviceaccount:default:workload-identity-sa'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\\r\\nTrace ID: 30b6df93-efd2-459c-ae6a-bad0838f6f00\\r\\nCorrelation ID: dffc6012-a4af-4f00-80ab-3e831069b3cc\\r\\nTimestamp: 2022-10-27 23:39:22Z\",\"error_codes\":[70021],\"timestamp\":\"2022-10-27 23:39:22Z\",\"trace_id\":\"30b6df93-efd2-459c-ae6a-bad0838f6f00\",\"correlation_id\":\"dffc6012-a4af-4f00-80ab-3e831069b3cc\",\"error_uri\":\"https://login.microsoftonline.com/error?code=70021\"}"
E1027 23:39:54.188948       1 token_credential.go:62] "failed to acquire token" err="FromAssertion(): http call(https://login.microsoftonline.com/78f9c33e-5b36-4730-93a8-9416d43ee1b3/oauth2/v2.0/token)(POST) error: reply status code was 400:\n{\"error\":\"invalid_request\",\"error_description\":\"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://kubernetes.default.svc.cluster.local'. Assertion Subject: 'system:serviceaccount:default:workload-identity-sa'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\\r\\nTrace ID: 105533fc-c40d-4aed-813d-86e5fc768c00\\r\\nCorrelation ID: ae6b4cd7-616a-4c09-b46c-5e094ffb05ec\\r\\nTimestamp: 2022-10-27 23:39:54Z\",\"error_codes\":[70021],\"timestamp\":\"2022-10-27 23:39:54Z\",\"trace_id\":\"105533fc-c40d-4aed-813d-86e5fc768c00\",\"correlation_id\":\"ae6b4cd7-616a-4c09-b46c-5e094ffb05ec\",\"error_uri\":\"https://login.microsoftonline.com/error?code=70021\"}"
E1027 23:40:54.860238       1 token_credential.go:62] "failed to acquire token" err="FromAssertion(): http call(https://login.microsoftonline.com/78f9c33e-5b36-4730-93a8-9416d43ee1b3/oauth2/v2.0/token)(POST) error: reply status code was 400:\n{\"error\":\"invalid_request\",\"error_description\":\"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://kubernetes.default.svc.cluster.local'. Assertion Subject: 'system:serviceaccount:default:workload-identity-sa'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\\r\\nTrace ID: 8dd718a9-dec1-40b5-9c78-f6deacf44d00\\r\\nCorrelation ID: bd002412-be3f-41ae-8a83-0ef8c6a2cd46\\r\\nTimestamp: 2022-10-27 23:40:54Z\",\"error_codes\":[70021],\"timestamp\":\"2022-10-27 23:40:54Z\",\"trace_id\":\"8dd718a9-dec1-40b5-9c78-f6deacf44d00\",\"correlation_id\":\"bd002412-be3f-41ae-8a83-0ef8c6a2cd46\",\"error_uri\":\"https://login.microsoftonline.com/error?code=70021\"}"

**Environment**

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by aramase** [comment]
1. `https://kubernetes.default.svc.cluster.local/` is not a valid issuer. For workload identity, the issuer needs to be reachable on the internet.
2. `No matching federated identity record found for presented assertion.` means no federated identity credential exists for the given issuer, service account name and namespace. Please refer to https://azure.github.io/azure-workload-identity/docs/topics/federated-identity-credential.html for setting up federated identity credential.

Here is our troubleshooting guide: https://azure.github.io/azure-workload-identity/docs/troubleshooting.html#aadsts70021-no-matching-federated-identity-record-found-for-presented-assertion

**Comment by mslearner** [comment]
Thank you for your input. I will try that.

**Comment by mslearner** [comment]
Do I need to set these variables also [(documented here)](https://azure.github.io/azure-workload-identity/docs/installation/self-managed-clusters/configurations.html)? I am using minikube and when I set these variables minikube does not boot up?
[--service-account-issuer]
[--service-account-signing-key-file]
[--service-account-key-file]
[--service-account-private-key-file]

**Comment by sozercan** [comment]
If you are using a self-managed cluster, you do need to set those. You would need to check the logs on apiserver or controller-manager for reasons.

**Comment by mslearner** [comment]
Here are the logs from the pod 

`E1029 05:55:04.865996       1 token_credential.go:62] "failed to acquire token" err="FromAssertion(): http call(https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token)(POST) error: reply status code was 401:\n{\"error\":\"invalid_client\",\"error_description\":\"AADSTS7000272: The certificate with identifier  used to sign the federated credential could not be found in the metadata of identity provider https://oidcissuerpd5678.blob.core.windows.net/oidc-test/. Please validate that your Identity Provider's metadata exposes the key used to sign the incoming token.\\r\\nTrace ID: 3f8cdd58-37a9-4f3f-8b22-4402c58f1900\\r\\nCorrelation ID: 8e54011d-d256-480a-bc7d-04022991c1fc\\r\\nTimestamp: 2022-10-29 05:55:04Z\",\"error_codes\":[7000272],\"timestamp\":\"2022-10-29 05:55:04Z\",\"trace_id\":\"3f8cdd58-37a9-4f3f-8b22-4402c58f1900\",\"correlation_id\":\"8e54011d-d256-480a-bc7d-04022991c1fc\",\"error_uri\":\"https://login.microsoftonline.com/error?code=7000272\"}"`

and here is the minikube command 

`minikube start --extra-config="apiserver.service-account-issuer=${SERVICE_ACCOUNT_ISSUER}" --extra-config="apiserver.service-account-signing-key-file=./sa.key" --extra-config="apiserver.service-account-key-file=./sa.pub" --extra-config="controller-manager.service-account-private-key-file=./sa.key" `

Above sa.key is the private key and sa.pub is the public key. The above command just hangs and minikube times out after a few minutes. Here are the logs 

`😄  minikube v1.27.1 on Ubuntu 22.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.25.2 on Docker 20.10.18 ...
    ▪ apiserver.service-account-issuer=https://oidcissuerpd5678.blob.core.windows.net/oidc-test/
    ▪ apiserver.service-account-signing-key-file=./sa.key
    ▪ apiserver.service-account-key-file=./sa.pub
    ▪ controller-manager.service-account-private-key-file=./sa.key`



` `

**Comment by mslearner** [comment]
The minikube problem will have to be handled in the minikube forum
