### ISSUE TITLE
Cannot create application using AZWI

### ISSUE THREAD

**Issue by mslearner** [Azure/azure-workload-identity#618]
**Describe the bug**

When I enter this command (as recommended in quick start)

`./azwi serviceaccount create phase app --aad-application-name "${APPLICATION_NAME}"`

**Steps To Reproduce**

**Expected behavior**

**Logs**
~/EnP/local_k8 $ ./azwi serviceaccount create phase app --aad-application-name "${APPLICATION_NAME}"
INFO[0000] No subscription provided, using selected subscription from Azure CLI: 01546fd2-2a1f-4430-8145-0945ec7c9ecf
Error: failed to run phase aad-application: failed to get AAD application: AzureCLICredential: ERROR: AADSTS530003: Your device is required to be managed to access this resource.

**Environment**
Linux bash shell

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by sozercan** [comment]
Sounds like error message contains the answer: `Your device is required to be managed to access this resource.`
