### ISSUE TITLE
workload identity tutorial (yaml file has some issue)

### ISSUE THREAD

**Issue by Jamal8548** [Azure/azure-workload-identity#657]
**Describe the bug**
After following the tutorial twice and doing all the steps as it is , we are unable to attain our goal.

**ERROR**
C:\Users\JamalAshraf>**kubectl get pods**
NAME          READY   STATUS   RESTARTS     AGE
quick-start   0/1     Error    1 (2s ago)   4s

C:\Users\JamalAshraf>**kubectl logs quick-start**
E1206 12:00:43.380355       1 main.go:60] "failed to get secret from keyvault" err="no Host in request URL" keyvault="azwi-ky-demo-013" secretName="my-secret"

**Steps To Reproduce**

**Expected behavior**

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by aramase** [comment]
@Jamal8548 Please share the following

1. `kubectl get pods -n <namespace where webhook is deployed>`
2. `kubectl get pod quick-start -o yaml`
3. service account yaml 
4. Logs from mutating webhook

Here is the troubleshooting guide: https://azure.github.io/azure-workload-identity/docs/troubleshooting.html

**Comment by Jamal8548** [comment]
thanks but it is working now as in pod we need now :
KEYVALUT_URL
