### ISSUE TITLE
AZURE_CLIENT_ID is not injected in test pod with user-assigned managed identity

### ISSUE THREAD

**Issue by pankaj-delphix** [Azure/azure-workload-identity#661]
**Describe the bug**
The environment variables are not injected

AZURE_AUTHORITY_HOST | The Azure Active Directory (AAD) endpoint.
-- | --
AZURE_CLIENT_ID | The client ID of the AAD application or user-assigned managed identity.
AZURE_TENANT_ID | The tenant ID of the registered AAD application or user-assigned managed identity.
AZURE_FEDERATED_TOKEN_FILE | The path of the projected service account token file.

**Steps To Reproduce**
Follow https://azure.github.io/azure-workload-identity/docs/installation.html to install to
- enable oidc
- install Mutating Admission Webhook using helm chart.
Follow https://azure.github.io/azure-workload-identity/docs/quick-start.html to testing the app. Use user-assigned managed identity and not Azure AD Application.
- ran `curl -sL https://github.com/Azure/azure-workload-identity/releases/download/v0.14.0/azure-wi-webhook.yaml | envsubst | kubectl apply -f -`

**Expected behavior**
AZURE_CLIENT_ID should be injected in the pod and `/var/run/secrets/azure/tokens/azure-identity-token` should be ceated

**Logs**

**Environment**
AKS cluster.

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**
It seems there is something missing in the documentation

**Comment by pankaj-delphix** [comment]
Things started working once i  registered the 'EnableWorkloadIdentityPreview' feature flag. So this is not a bug. Please close it.
Just wanted to check which method is recommended
1. One mention @ https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity
2. One mentioned @ https://azure.github.io/azure-workload-identity/docs/introduction.html

**Comment by aramase** [comment]
If you're using AKS, the recommendation is to the AKS add-on (https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity). It's a managed version of this project that's supported.
