### ISSUE TITLE
webhook:v0.15.0 not available in MCR

### ISSUE THREAD

**Issue by FlorianZieglerFeuerbach** [Azure/azure-workload-identity#674]
**Describe the bug**

When updating to the latest version 0.15.0, we cannot pull the webhook:v0.15.0 image.

On further investigation, the image is not available in MCR at the location given in azure-wi-webhook.yaml.

**Steps To Reproduce**

`docker pull mcr.microsoft.com/oss/azure/workload-identity/webhook:v0.15.0`

**Expected behavior**

Container image webhook:v0.15.0

**Logs**

```
$ docker pull mcr.microsoft.com/oss/azure/workload-identity/webhook:v0.15.0
Error response from daemon: manifest for mcr.microsoft.com/oss/azure/workload-identity/webhook:v0.15.0 not found: manifest unknown: manifest tagged by "v0.15.0" is not found
```

**Comment by aramase** [comment]
Images were just published. They should be available now.
