### ISSUE TITLE
Can this be used for things other than keyvault?

### ISSUE THREAD

**Issue by tdevopsottawa** [Azure/azure-workload-identity#677]
I'm trying to use AZWI to provide az login credentials to an Azure CLI pod inside kubernetes (using the Azure CLI docker image) and not sure if this is possible and if so how to actually do it. The documentation only talks about how to use AZWI to pull secrets from keyvault and it's unclear if other use cases are possible or how do to them.

**Comment by aramase** [comment]
If you need to use it with azure cli, you can run the following command in the pod

```bash
az login --federated-token "$(cat  $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID
```

It works with all azure resources. We only have examples here with the key vault SDK reference. It would be similar with other azure resources.

**Comment by tdevopsottawa** [comment]
@aramase doesn't work.. when I try to add that line it just hangs forever with no output
