### ISSUE TITLE
When will it be production ready?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-workload-identity#689]
Hello,

Happy new year to everyone.

Currently this project is in [preview ](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview)mode. When will it be production ready or GA. 

We need to plan the migration from AAD to Azure workload.. Any updates please?

Thank you.

Kind Regards,
Tanul

**Comment by tjrobinson** [comment]
This has been answered in: https://github.com/Azure/azure-workload-identity/discussions/471#discussioncomment-4594585

> The AKS GA is tentatively planned for March.
> 
> @miwithro for updates on the timeline in case of changes.

**Comment by smartaquarius10** [comment]
@tjrobinson, Thank you so much 😄
