### ISSUE TITLE
Access Token couldnot be aquired while using workload identity 

### ISSUE THREAD

**Issue by poadhika** [Azure/azure-workload-identity#725]
**Describe the bug**
We have a job that was using aad pod identity. In the .net app it uses azure service token provider to fetch the necessary token. After switching to workload identity, I am getting following error:

The logging instrumentation key is /var/run/mdsd/default_fluent.socket
Unhandled exception: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: RunAs=App;AppId=########## Resource: https://database.windows.net/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Failed after 5 retries. MSI ResponseCode: NotFound, Response: clientID in request: d937##### REDACTED #####064c, getting assigned identities for pod ################### in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors

   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(String resource, String tenantId, Boolean forceRefresh, CancellationToken cancellationToken)

**Comment by aramase** [comment]
@poadhika what steps did you take to migrate to WI? The above log indicates the application is still using the old version of sdk to get a token for managed identity. The minimum required sdk versions are documented here: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html. In addition to the minimum sdk version, you'll also need to configure the federated identity credential and ensure you're using the correct service account: https://azure.github.io/azure-workload-identity/docs/quick-start.html

**Comment by poadhika** [comment]
Thank you for your response. Following is the response:

Azure IdentityVersion used: 1.8.1
I basically followed all the steps described here: https://azure.github.io/azure-workload-identity/docs/quick-start.html

The steps were:
1.Service account is created with approproate annotations
2. Used managed identity is federated.
3. Workload pod has appropriate annotations and serviceaccount.
4. Removed the addpodidentitybinding label from workload pod.

That is where my confusion is. We are following all the steps stated to migrate to workload identity and still we are not able to make it work.

**Comment by almir0** [comment]
How does your container code look like? Are you using DefaultAzureCredentials?

**Comment by aramase** [comment]
@poadhika Is this issue resolved?

**Comment by aramase** [comment]
@poadhika confirmed the issue is resolved!
