### ISSUE TITLE
Azure MySQL token based auth from pod

### ISSUE THREAD

**Issue by bugie** [Azure/azure-workload-identity#727]
We are migrating a working solution from AAD Pod ID to Workload ID. The pod needs to be able to generate a token based on the assigned managed ID to be used for access to an Azure MySQL database. Logs below show that we are not able to generate a token and we have not been able to find the correct solution. 

**Steps To Reproduce**
Followed documentation to setup the AKS Cluster and deploy: https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster

Followed documentation to update application:  https://learn.microsoft.com/en-us/azure/app-service/tutorial-connect-msi-azure-database?tabs=mysql%2Cuserassigned%2Cjava%2Cvscode#tabpanel_12_mysql

**Logs**
`2023-01-31 15:27:36.308 ERROR 7 --- [       Thread-0] c.a.identity.ManagedIdentityCredential   : Azure Identity => ERROR in getToken() call for scopes [https://ossrdbms-aad.database.windows.net]: Managed Identity authentication is not available."`

`Caused by: com.microsoft.aad.msal4j.MsalAzureSDKException: java.util.concurrent.ExecutionException: java.io.IOException: Server returned HTTP response code: 400 for URL: https://login.microsoftonline.com/{TENANT}/oauth2/v2.0/token"`

**Environment**
- Kubernetes version (use `kubectl version`): AKS 1.23.12
- Region: West Europe

**Additional context**
We have gone over the settings such as pod labels and annotations. Service account annotation and serviceAccoutName in the pod. We can run `az identity federated-credential list` on the managed ID and see that it is correct. Based on the documentation we can not find the missing step or what the Error messages refer to. 
azure-wi-webhook-controller-manager logs have not provided any useful information either.

**Comment by aramase** [comment]
@bugie please confirm you're using the minimum required sdk version for workload identity: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html.

**Comment by bugie** [comment]
@aramase, Thank you for having a look. Our pom.xml defines 1.7.0. I see [1.8.0](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-identity_1.8.0) was released a couple days ago. 

` <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.7.0</version>
    </dependency>`

**Comment by bugie** [comment]
@aramase, We seem to have found some success today.
`Azure Identity => getToken() result for scopes [https://ossrdbms-aad.database.windows.net/.default]: SUCCESS"`

The update to the scope is not part of the documentation for Azure MySQL but seems to resolve the issue. Do you know what significance the addition of `/.default` has?
