### ISSUE TITLE
unable to get secrets: ... "Identity not found"

### ISSUE THREAD

**Issue by MattMencel** [Azure/azure-workload-identity#728]
**Describe the bug**

Application cannot access Key Vault.

> unable to get secrets: azureBearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://MYKEYVAULTURI/secrets?api-version=2016-10-01&maxresults=1: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=MYCLIENTID&resource=https%3A%2F%2Fvault.azure.net

**Steps To Reproduce**

I've followed the docs.
- enabled wi and oidc on the AKS cluster
- created a user assigned identity
- created the federated id credential
- assigned the MID as the "Key Vault Secrets User" role on the keyvault
- added the annotations and labels to the k8s ServiceAccount
- assigned that ServiceAccount to my pods

**Expected behavior**

Pods are able to retrieve secrets from the Key Vault

**Logs**

See above...

**Environment**

- Kubernetes version (use `kubectl version`): `"v1.23.12`
- Cloud provider or hardware configuration: `Azure AKS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 18.04.6 LTS`
- Kernel (e.g. `uname -a`): `Linux aks-platform-38448096-vmss000000 5.4.0-1098-azure #104~18.04.2-Ubuntu SMP Tue Nov 29 12:13:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Terraform/CLI

**Additional context**

I found a comment in a [StackOverflow thread](https://stackoverflow.com/questions/75093624/azure-aks-container-app-cant-access-key-vault-using-managed-identity#comment132635052_75126441) that is similar to my issue. 

It mentions putting the CSI Secrets identity in the ServiceAccount as a workaround. As soon as I put the `addonProfiles.azureKeyvaultSecretsProvider.identity.clientId` in the `azure.workload.identity/client-id:` ServiceAccount annotation, it started working.

I'm not sure why the Workload Identity MI wouldn't work. It seems like it was able to contact the KeyVault, but the KV did not think it was a valid identity, even though the MI was assigned to the KV with the "Key Vault Secrets User" role.

The documentation mentions using "Access Policies", but not AAD "Role Assignments" on the Key Vault. It should work either way though I would think.

**Comment by aramase** [comment]
@MattMencel AKV provider for Secrets Store CSI Driver doesn't require the webhook/annotation that's documented in this repo. The CSI driver gets the WI token as part of the volume mount request and uses that. Steps for using WI with CSI driver is documented here: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/workload-identity-mode/. Please refer to that for setup and if you have any questions, feel free to open an issue [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues).

**Comment by MattMencel** [comment]
@aramase can we reopen this? My question wasn't about the CSI driver.... It's about WI.

I've followed the [documentation](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster) to setup WI and enable it on my pods, but I get the error indicated in my first comment. Essentially...  **"Identity not found"**

I'd like for this to work. The CSI driver identity is just a workaround until I can get the managed identity working.

**Comment by aramase** [comment]
> @aramase can we reopen this? My question wasn't about the CSI driver.... It's about WI.
> 
> I've followed the [documentation](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster) to setup WI and enable it on my pods, but I get the error indicated in my first comment. Essentially... **"Identity not found"**
> 
> I'd like for this to work. The CSI driver identity is just a workaround until I can get the managed identity working.

@MattMencel The CSI driver doesn't use the workload identity components from this repo. For workload identity with CSI driver, the service account tokens are passed to the AKV provider as part of volume mount request. 

`Identity not found` is only when you're using user-assigned managed identity to access AKV. If you're using workload identity, then you need to configure the client id of the identity in `clientID` field of SecretProviderClass as mentioned in the docs.

**Comment by MattMencel** [comment]
@aramase agreed, and that's what I did. I created a managed identity, added the federated credential, then put the MI ClientID on the ServiceAccount in Kubernetes.

``` yaml
azure.workload.identity/client-id: MI_CLIENT_ID_HERE
```

This produces the `Identity not found` error for me.

**Comment by aramase** [comment]
@MattMencel The service account annotation is not required for the CSI driver as it doesn't use the mutating webhook. Did you get a chance to look at the steps for the link I shared? https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/identity-access-modes/workload-identity-mode/. This doc is the steps need for using WI with CSI driver.

**Comment by MattMencel** [comment]
@aramase my original question was how to use WI with a managed identity, not the CSI driver. 

If the CSI driver is the only way to make it work, that's fine I guess, but it wasn't my question.

**Comment by avdicl** [comment]
Why does Azure have thorough documentation on getting WI working with a user-assigned managed identity if it just doesn't work without the use of the CSI driver? For WI specifically, the CSI driver is not listed as a requirement so what do they expect users who require this feature to do? I get that it's still in Preview, no need for a reminder. 

@MattMencel From the StackOverflow thread you shared, I can confirm the use cases discussed. Instead of using the CSI driver as a workaround for a new user-assigned managed identity, I just used the user-assigned managed identity that was automatically generated for the nodes upon cluster initiation. Adding an Access Policy for the aforementioned MI and adding the required serviceaccount annotations/labels works. Not my ideal solution but I'd rather leverage this over the CSI driver hack.
