### ISSUE TITLE
How to migrate from `aad-pod-identity`?

### ISSUE THREAD

**Issue by 64J0** [Azure/azure-workload-identity#731]
**Is your feature request related to a problem? Please describe.**

Hello, hope you're good. I noticed recently that the `aad-pod-identity` project is being retired in favor of this project. Is there any migration tutorial, describing what to do if we were using this old project?

**Describe the solution you'd like**

- A section in the documentation about migrating from the `aad-pod-identity` tool.

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
Hello 👋🏻  you can refer to https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity.

tl;dr: 
1. If you use `DefaultAzureCredential` in your workload, you can update the azure identity sdk version to the latest that supports workload identity (ref: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html)
2. If you still have workloads that get managed identity token from IMDS, you can annotate the pod to get a proxy sidecar injected, that'll do the token exchange with the new flow.

**Comment by 64J0** [comment]
All right, thanks for this information @aramase! If no one do it first, I'm going to add this information to this project's documentation.

**Comment by 64J0** [comment]
Done, created this PR: https://github.com/Azure/azure-workload-identity/pull/732. With this in mind, I'm going to close this issue. Thanks again @aramase.
