### ISSUE TITLE
[Question] Steps of implementing AAD Workload Identity

### ISSUE THREAD

**Issue by lesscodingmorehappiness** [Azure/azure-workload-identity#783]
Hi,

I have followed https://azure.github.io/azure-workload-identity/docs/quick-start.html and the output are same as the example. But I have few questions about implementing it to our real project:

1. The steps in [quick-start](https://azure.github.io/azure-workload-identity/docs/quick-start.html) are all steps required to implement AAD Workload Identity? 
2. From my understanding the image (ghcr.io/azure/azure-workload-identity/msal-go) used in [deploy-workload](https://azure.github.io/azure-workload-identity/docs/quick-start.html#7-deploy-workload) is just an example? For a real project, we just need to change it to our image? Do we need to do any other setups or code changes?
3. From the doc, with AAD Workload Identity, AAD should give access token to workloads, not secrets (e.g. keyvault secret), is that correct? And /var/run/secrets/azure/tokens is the path where the token should be found within the pod?
4. Does AAD workload Identity only work for kubernetes pods? Can we use it to generate token for API server?
5. Is there any microsoft alias email that we can contact to start a thread if needed?

Thanks.

**Comment by aramase** [comment]
> The steps in [quick-start](https://azure.github.io/azure-workload-identity/docs/quick-start.html) are all steps required to implement AAD Workload Identity?

Those steps include creating Key vault and providing permissions for the demo, but those steps might not be necessary for you. You'll need to create the identity and provide it access to the Azure resource for your workload. The rest of the steps will be applicable for every workload.

> From my understanding the image (ghcr.io/azure/azure-workload-identity/msal-go) used in [deploy-workload](https://azure.github.io/azure-workload-identity/docs/quick-start.html#7-deploy-workload) is just an example? For a real project, we just need to change it to our image? Do we need to do any other setups or code changes?

For your workload, you'll already have a pod spec. You'll need to add the required [labels and annotations](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#pod). Also, your workload needs to use the sdk to obtain a token using workload identity. There are some examples and minimum required versions here: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html

> From the doc, with AAD Workload Identity, AAD should give access token to workloads, not secrets (e.g. keyvault secret), is that correct? And /var/run/secrets/azure/tokens is the path where the token should be found within the pod?

Not sure I understand this question. Yes `/var/run/secrets/azure/tokens` is the token path inside the pod and that path is also set as an env var `AZURE_FEDERATED_TOKEN_FILE`. That env var is used by sdks and can also be used by the workload to know the token path. 

> Does AAD workload Identity only work for kubernetes pods? Can we use it to generate token for API server?

Can you elaborate on what token is generated here for API server?

> Is there any microsoft alias email that we can contact to start a thread if needed?

You can reach out to us via GitHub issues or discussions. If there is something internal, you can reach out to us internally on teams.

**Comment by lesscodingmorehappiness** [comment]
> For your workload, you'll already have a pod spec. You'll need to add the required [labels and annotations](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#pod). Also, your workload needs to use the sdk to obtain a token using workload identity. There are some examples and minimum required versions here: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html

From [labels and annotations](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#pod), seems the only '**Required**' one is _azure.workload.identity/use_ ? 
Also I'm a bit confused about the [Service Account](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#service-account) section in this page. If we use AKS I think we can ignore this part?

> Not sure I understand this question. Yes /var/run/secrets/azure/tokens is the token path inside the pod and that path is also set as an env var AZURE_FEDERATED_TOKEN_FILE. That env var is used by sdks and can also be used by the workload to know the token path.

Let me try to make the question more clear: I think '_access token_' is a different thing from '_KeyVault secrets_' (or KeyVault keys), correct? From the doc, the Workload Identity is supposed to get '_access token_' for workloads to access Azure resources, while in the example it's getting the _KeyVault secrets_. I'm confused about this part. 

I took a look at the code and found the function [GetToken](https://github.com/Azure/azure-workload-identity/blob/main/examples/msal-go/token_credential.go#L50) but I didn't see reference of it. Is this the function that we should use to actually get azure access token for workloads? Is there any example of calling it?

Thanks

**Comment by lesscodingmorehappiness** [comment]
Oh I think I misunderstood the example. The case should be: in the example in quick-start, the keyvault is the 'Azure resource' that kubernetes pod wants to access. Is this correct?
