### ISSUE TITLE
LogLevel not supported on /manager binary

### ISSUE THREAD

**Issue by mdhomer** [Azure/azure-workload-identity#786]
**Describe the bug**
I'm trying to enable `trace` with the released beta chart:
```
dependencies:
  - name: workload-identity-webhook
    version: 1.0.0-beta.0
    repository: https://azure.github.io/azure-workload-identity/charts
```

config specified in values.yaml
```
workload-identity-webhook:
  azureTenantID: "<my tenant id>"
  logLevel: trace
```

We were previously testing using chart v0.15.0 however this option was not supported by config or passed through to the `/manager` binary.

**Steps To Reproduce**

Noted in information above.

**Expected behavior**

/managed binary has support for -log-level flag, and this results in more logs than the default "info" level logging in the controller-manager pods.

**Logs**

Failing pod logs.
```
kubectl logs -n azure-workload-identity-system azure-wi-webhook-controller-manager-649855697f-xltkp

flag provided but not defined: -log-level
Usage of /manager:
  -add_dir_header
    	If true, adds the file directory to the header of the log messages
  -alsologtostderr
    	log to standard error as well as files (no effect when -logtostderr=true)
  -arc-cluster
    	Running on arc cluster
  -audience string
    	Audience for service account token
  -disable-cert-rotation
    	disable automatic generation and rotation of webhook TLS certificates/keys
  -health-addr string
    	The address the health endpoint binds to (default ":9440")
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
  -log-encoder string
    	Sets the log encoder (console|json) (default "console")
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory (no effect when -logtostderr=true)
  -log_file string
    	If non-empty, use this log file (no effect when -logtostderr=true)
  -log_file_max_size uint
    	Defines the maximum size a log file can grow to (no effect when -logtostderr=true). Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
    	log to standard error instead of files (default true)
  -metrics-addr string
    	The address the metrics endpoint binds to (default ":8095")
  -metrics-backend string
    	Backend used for metrics (default "prometheus")
  -one_output
    	If true, only write logs to their native severity level (vs also writing to each lower severity level; no effect when -logtostderr=true)
  -skip_headers
    	If true, avoid header prefixes in the log messages
  -skip_log_headers
    	If true, avoid headers when opening log files (no effect when -logtostderr=true)
  -stderrthreshold value
    	logs at or above this threshold go to stderr when writing to files and stderr (no effect when -logtostderr=true or -alsologtostderr=false) (default 2)
  -tls-min-version string
    	Minimum TLS version (default "1.3")
  -v value
    	number for the log level verbosity
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
  -webhook-cert-dir string
    	Webhook certificates dir to use. Defaults to /certs (default "/certs")
```

**Environment**

- Kubernetes version (use `kubectl version`): v1.25.5
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by aramase** [comment]
@mdhomer What version of the webhook are you using? If you're using `v0.15.0` image of the webhook with different version of the chart (`v1.0.0-beta.0`), it'll fail as these flags are new. The chart and image version need to be in sync.

**Comment by mdhomer** [comment]
I tried it with both versions, but most recently the workload-identity-webhook `1.0.0-beta.0`, published here https://azure.github.io/azure-workload-identity/charts.

Based on the current docs: https://github.com/Azure/azure-workload-identity/tree/main/charts/workload-identity-webhook#parameters and the default values file.

The current `image.release` value is set to Current release version: `v1.0.0-beta.0`.
https://github.com/Azure/azure-workload-identity/blob/main/charts/workload-identity-webhook/values.yaml#L10

**Comment by aramase** [comment]
> The current image.release value is set to Current release version: v1.0.0-beta.0.
https://github.com/Azure/azure-workload-identity/blob/main/charts/workload-identity-webhook/values.yaml#L10

The helm charts have the correct image and we set `logLevel` to `info` explicitly in the values file. This is all validated as part of the CI and works as expected. I also confirmed the error you posted only shows up if you're using the latest chart with an older release image of webhook that doesn't support the flags.

```bash
➜ helm install wi azure-workload-identity/workload-identity-webhook --set azureTenantID=<tenant id> --create-namespace --namespace azure-workload-identity-system --set logLevel=trace --devel
NAME: wi
LAST DEPLOYED: Tue Mar 21 18:18:26 2023
NAMESPACE: azure-workload-identity-system
STATUS: deployed
REVISION: 1
TEST SUITE: None

➜ helm ls -A
NAME	NAMESPACE                     	REVISION	UPDATED                                	STATUS  	CHART                                 	APP VERSION
wi  	azure-workload-identity-system	1       	2023-03-21 18:18:26.037432973 +0000 UTC	deployed	workload-identity-webhook-1.0.0-beta.0	v1.0.0-beta.0

➜ kgp -l app=workload-identity-webhook -n azure-workload-identity-system
NAME                                                   READY   STATUS    RESTARTS   AGE
azure-wi-webhook-controller-manager-5cb8b979b9-f5m7x   1/1     Running   0          16s
azure-wi-webhook-controller-manager-5cb8b979b9-sdb24   1/1     Running   0          16s

➜ kgp -l app=workload-identity-webhook -n azure-workload-identity-system -oyaml | grep image:
      image: mcr.microsoft.com/oss/azure/workload-identity/webhook:v1.0.0-beta.0
```

You would need to check if you're overwriting the image to an older release as part of your deployment. Using `1.0.0-beta.0` with `v1.0.0-beta.0` image should work as expected.

**Comment by mdhomer** [comment]
Its possible the image value was retained from a previous helm release of the chart. I'll try replicate and confirm tomorrow. Thanks for the confirmation on your end!

**Comment by aramase** [comment]
> Its possible the image value was retained from a previous helm release of the chart. I'll try replicate and confirm tomorrow. Thanks for the confirmation on your end!

did you get a chance to confirm?

**Comment by aramase** [comment]
I'm going to close this issue with https://github.com/Azure/azure-workload-identity/issues/786#issuecomment-1478386071. Please feel free to reopen if your results post confirmation.
