### ISSUE TITLE
[Question] How to "heal" dependent pods in CrashLoopBackOff?

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/azure-workload-identity#790]
I am doing some testing with AKS start/stop cluster functionality in my cluster where several deployments use workload identity. This works fine for the most part, however in a couple of my namespaces my pods are stuck with the exception

`at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(Token ...`

For the pods which are in a crash loop, I notice that the env vars such as `AZURE_FEDERATED_TOKEN_FILE, AZURE_AUTHORITY HOST`, etc. are not set. I don't know if this is expected or not.

If I delete the affected pods, they are recreated and are able to use workload identity straight away. Are there any config changes I could make to avoid this situation?

**Comment by audunsolemdal** [comment]
The deployments in question also have liveness & startup probes set with maxRetries, unsure if this makes a difference or not.

**Comment by audunsolemdal** [comment]
It seems like this also causes issues for pods not in CrashLoopBackOff. There are pods in my cluster which have been running for 36 hours after restart of the cluster, without any of the `AZURE_X X` env variables set by workload identity

**Comment by nilsgstrabo** [comment]
We experienced the same when running v0.15.0 (and lower).
The MutatingWebookConfiguration's failurePolicy was set to Ignore, and if AWI was not ready (or failed to respond to webhook mutation requests), your Pods would still be created, but without the required workload identity envvars and volumes.

In v1.0.0-alpha.0 the failurePolicy is set to Fail, which will prevent Pods with label `azure.workload.identity/use: "true"` from being created if AWI does not respone to mutation requests.

**Comment by aramase** [comment]
@audunsolemdal as @nilsgstrabo mentioned, we have changed the `failurePolicy` to `Fail` in the pre-releases of `v1.0.0`. That will cause pods that depend on the mutating webhook to not start until the webhook is up and running. Check out the release notes: https://github.com/Azure/azure-workload-identity/releases/tag/v1.0.0-beta.0.

I'm going to close this issue. Give the beta release a try and let us know if you run into any issues. The `v1.0.0` release is planned for next week.
