### ISSUE TITLE
Azure Defender - Recommendation to Disable Automounting ServiceCredential

### ISSUE THREAD

**Issue by srisujan** [Azure/azure-workload-identity#798]
**Describe the bug**
azure-wi-webhook-controller-manager pods are being recommended to disable automounting service credentails. We dont see the values.yaml file supporting to override the values for securityContext
**Steps To Reproduce**

**Expected behavior**
The controller manager pods shouldnt show up in Azure Defender Recommendation

**Logs**

**Environment**

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by aramase** [comment]
@srisujan The serviceaccount token are required for the workload identity mutating webhook, so auto mount of service account token can't be disabled. For workload identity, to comply the recommendation I would recommend deploying the webhook in `kube-system` namespace.  If deployed in `kube-system`, you'll no longer see the alerts.

Closing this issue with the action item. Feel free to reopen if you run into any issues.
