### ISSUE TITLE
Azure 1st Party using Workload Identity get AADSTS700222 Error

### ISSUE THREAD

**Issue by tshaiman** [Azure/azure-workload-identity#820]
we are 1st Party of Azure ,and we have followed the installation guide at the quick start 
https://azure.github.io/azure-workload-identity/docs/quick-start.html

- we need to use AAD App a workload deployed on East Asia. since EA does not support User Assigned MI , we must use AAD App.
-  during the quick-start guide we follow the path of creating against AAD App.
- once the pod is up and running we can see the following environment variable : 

```
      AZURE_FEDERATED_TOKEN_FILE:  /var/run/secrets/azure/tokens/azure-identity-token
      AZURE_AUTHORITY_HOST:        https://login.microsoftonline.com/
```

since we know that according to [this article](https://learn.microsoft.com/en-us/azure/active-directory/workload-identities/workload-identity-federation-considerations#azure-active-directory-issuers-arent-supported) if the issuer is *.login.microsoftonline.com 
then the scenario is not supported.

**we want to know how can we change the AZURE_AUTHORITY_HOSTS as this is not configurable during the quick-start guide.**

**Steps To Reproduce**
- follow the quick start guide as 1st Party 

**Expected behavior**
- we want to know how can we change the AZURE_AUTHORITY_HOSTS as this is not configurable during the quick-start guide.

**Logs**
```
E0330 21:23:35.283457       1 main.go:60] "failed to get secret from keyvault" err=<
        FromAssertion(): http call(https://login.microsoftonline.com/33e01921-4d64-4f8c-a055-5bdaffd5e33d/oauth2/v2.0/token)(POST) error: reply status code was 400:
        {"error":"invalid_request","error_description":"AADSTS700223: Only AAD-issued tokens may be used for first-party application federated identity flows.\r\nTrace ID: 15b62857-4f8b-4501-986d-1c4230750400\r\nCorrelation ID: 5b4fdabf-14c2-4c7b-b401-62c4f8d65d73\r\nTimestamp: 2023-03-30 21:23:35Z","error_codes":[700223],"timestamp":"2023-03-30 21:23:35Z","trace_id":"15b62857-4f8b-4501-986d-1c4230750400","correlation_id":"5b4fdabf-14c2-4c7b-b401-62c4f8d65d73","error_uri":"https://login.microsoftonline.com/error?code=700223"}
 > keyvault="https://vi-prod-map-ea-kv.vault.azure.net/" secretName="HelloSecret"
```

**Environment**

- Kubernetes version (use `kubectl version`): 1.25.5
- Cloud provider or hardware configuration: Azure / 1st Party Tenant 
- OS (e.g: `cat /etc/os-release`): Linux
- Network plugin and version (if this is a network-related bug): kubenet
- Others: Region : East Asia

**Additional context**
- is there a way during the creation of the AAD App that we can change the Authority Host ? 
we simply follow the getting-started guide and it says nothing about how to change this URL 
I guess this is inhertied from the Directoy you are assigned to . 
if this is true : does it mean that we as 1st Party cannot use this feature with AAD Apps ?

**Comment by aramase** [comment]
There is no change required in WI here and there is already an internal thread for this. Closing this issue to avoid duplication.
