### ISSUE TITLE
User forbidden error

### ISSUE THREAD

**Issue by tanumoy94** [Azure/azure-workload-identity#823]
**Describe the bug**
Getting forbidden user while applying azure-wi-webhook.yaml. All the resources are getting created without any issue, but controller manager pods are failing to start.

**Steps To Reproduce**
1. wget azure-wi-webhook.yaml
2. Update AZURE_TENANT_ID and AZURE_ENVIRONMENT in azure-wi-webhook-config configmap section
3. Deploy yaml (kubectl create -f azure-wi-webhook.yaml)

**Expected behavior**

Controller manager pods should be up and running

**Actual behavior**

Readiness failing for Controller manager pods

**Logs**

```
/cert-controller@v0.5.0/pkg/rotator/rotator.go:777$rotator.(*CertRotator).ensureReady","message":"CA certs are injected to webhooks"}
{"level":"info","timestamp":"2023-04-04T05:48:09.493158Z","logger":"entrypoint","caller":"/workspace/main.go:162$main.setupWebhook","message":"registering webhook to the webhook server"}
{"level":"info","timestamp":"2023-04-04T05:48:09.493272Z","logger":"controller-runtime.webhook.webhooks","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/webhook/server.go:216$webhook.(*Server).Start","message":"Starting webhook server"}
{"level":"info","timestamp":"2023-04-04T05:48:09.493332Z","logger":"controller-runtime.webhook","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/webhook/server.go:148$webhook.(*Server).Register","message":"Registering webhook","path":"/mutate-v1-pod"}
{"level":"info","timestamp":"2023-04-04T05:48:09.493552Z","logger":"controller-runtime.certwatcher","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/certwatcher/certwatcher.go:131$certwatcher.(*CertWatcher).ReadCertificate","message":"Updated current TLS certificate"}
{"level":"info","timestamp":"2023-04-04T05:48:09.493663Z","logger":"controller-runtime.webhook","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/webhook/server.go:270$webhook.(*Server).Start","message":"Serving webhook server","host":"","port":9443}
{"level":"info","timestamp":"2023-04-04T05:48:09.493758Z","logger":"controller-runtime.certwatcher","caller":"/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/certwatcher/certwatcher.go:85$certwatcher.(*CertWatcher).Start","message":"Starting certificate watcher"}
{"level":"info","timestamp":"2023-04-04T05:48:35.286993Z","logger":"cert-rotation","caller":"/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.5.0/pkg/rotator/rotator.go:722$rotator.(*ReconcileWH).ensureCerts","message":"Ensuring CA cert","name":"azure-wi-webhook-mutating-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration","name":"azure-wi-webhook-mutating-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration"}
{"level":"error","timestamp":"2023-04-04T05:48:35.293159Z","logger":"cert-rotation","caller":"/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.5.0/pkg/rotator/rotator.go:729$rotator.(*ReconcileWH).ensureCerts","message":"Error updating webhook with certificate","name":"azure-wi-webhook-mutating-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration","error":"mutatingwebhookconfigurations.admissionregistration.k8s.io \"azure-wi-webhook-mutating-webhook-configuration\" is forbidden: User \"system:serviceaccount:azure-workload-identity-system:azure-wi-webhook-admin\" cannot update resource \"mutatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope"}
```

**Environment**

- Kubernetes version: v1.25.4
- Cloud provider or hardware configuration: Azure

**Additional context**

**Comment by aramase** [comment]
The error message indicates you don't have the required `ClusterRole` configured (xref: https://github.com/Azure/azure-workload-identity/blob/59b83f2af43039f5eab3b6027c303020a7078f61/deploy/azure-wi-webhook.yaml#L44-L68). If you applied the [yaml](https://github.com/Azure/azure-workload-identity/blob/main/deploy/azure-wi-webhook.yaml) it should work. I validated it on my cluster and this is also validated as part of the CI.

**Comment by tanumoy94** [comment]
I can see clusterrole is deployed properly. but still the same error. I used the same yaml you mentioned in your comments above.

`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","azure-workload-identity.io/system":"true","kubernetes.azure.com/managedby":"aks"},"name":"azure-wi-webhook-manager-role"},"rules":[{"apiGroups":[""],"resources":["serviceaccounts"],"verbs":["create","get","list","patch","update","watch"]},{"apiGroups":["admissionregistration.k8s.io"],"resources":["mutatingwebhookconfigurations"],"verbs":["create","delete","get","list","patch","update","watch"]}]}
  creationTimestamp: "2023-04-05T04:14:11Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    azure-workload-identity.io/system: "true"
    kubernetes.azure.com/managedby: aks
  name: azure-wi-webhook-manager-role
  resourceVersion: "121294900"
  uid: 9e288391-5ec5-4981-a13e-20122f22ec2d
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch`

**Comment by aramase** [comment]
`kubernetes.azure.com/managedby: aks` indicates this `ClusterRole` is managed as part of the AKS add-on. If you have the add-on enabled for WI, you don't need to deploy again using the manifests from this repo.

Closing this issue because it seems like duplicate install of workload identity. Please do a clean install either with the deploy yaml from this repo or by just enabling the AKS add-on (https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview).
