### ISSUE TITLE
Federated Credential Quota Increase request

### ISSUE THREAD

**Issue by poadhika** [Azure/azure-workload-identity#830]
We are in the process of migrating to workload idenity however, we are constantly rre-qriting the code to get around this federated identity credential limit which is making this transition more difficult. Is there a plan to increase this limit to more than 20?  This is blocking the complete transition of our service to workload identity,

**Comment by aramase** [comment]
This is a duplicate of https://github.com/Azure/azure-workload-identity/issues/575.

@poadhika This is an AAD limitation. AFAIK there is currently no plan to increase it. This can be resolved with the wildcard support as requested [here](https://github.com/Azure/azure-workload-identity/issues/373) which is again an AAD feature.

Closing this as duplicate.
