### ISSUE TITLE
How to deal with applications in multiple namespaces?

### ISSUE THREAD

**Issue by 64J0** [Azure/azure-workload-identity#837]
**Is your feature request related to a problem? Please describe.**

The current documentation presented in Azure ([link](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity) - step 4), describe the setup for a single namespace in AKS.

Some questions that appear after reading this piece of documentation are:

- What is the recommended way to configure this tool to work in multiple namespaces?
  - Do I need to create one service account per namespace?
  - Can I re-use the same identity in other namespaces?
  - Can I use this command `az identity federated-credential create --name $federatedIdentityName --identity-name $UAMI --resource-group $resourceGroupName --issuer ${AKS_OIDC_ISSUER} --subject system:serviceaccount:${serviceAccountNamespace}:${serviceAccountName}` appending other namespaces into it?

**Describe the solution you'd like**

I would like to have access to a more general documentation, that specify the steps for a scenario that you have a single namespace and for many namespaces.

**Describe alternatives you've considered**

I'm considering running those tests myself, but if it's available in some documentation would be better.

**Additional context**

**Comment by aramase** [comment]
> Do I need to create one service account per namespace?

Kubernetes service accounts are namespaced resources, so you need to create in the same namespace as the pod to be able to reference it.

> Can I re-use the same identity in other namespaces?

There is no restriction on this. An identity can be used in multiple namespaces. The subject configured in the federated identity credential (FIC) is a combination of <service account namespace, service account name>, so you'll need to create a FIC for every namespace the service account is in.

> Can I use this command az identity federated-credential create --name $federatedIdentityName --identity-name $UAMI --resource-group $resourceGroupName --issuer ${AKS_OIDC_ISSUER} --subject system:serviceaccount:${serviceAccountNamespace}:${serviceAccountName} appending other namespaces into it?

No, you can't append namespaces. Subject is a unique string and for the service account token it's `system:serviceaccount:<service account namespace>:<service account name>`.

> I would like to have access to a more general documentation, that specify the steps for a scenario that you have a single namespace and for many namespaces.

Multiple namespaces is just the construct in the cluster. In case of configuration, there is no difference for a single/multiple namespace. The FIC needs to be configured for every service account that needs to be used with the identity.
