### ISSUE TITLE
Clarify which Service Account Labels and Annotations are required

### ISSUE THREAD

**Issue by rgl** [Azure/azure-workload-identity#859]
**Is your feature request related to a problem? Please describe.**

Kinda. With the recent v1.0.0 breaking change of making `azure.workload.identity/use` required in a Pod but optional in a Service Account, the documentation was modified by adding a `Required` column in some tables, but I think, to make things clear/consistent, that it needs to be added in all the other tables too.

**Describe the solution you'd like**

All the [Service Account Labels and Annotations](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#service-account-labels-and-annotations) tables should have a "Required" column to make it clear which labels and annotations are required.

That would make all the tables consistent with each others.

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
Closed with https://github.com/Azure/azure-workload-identity/pull/860
