### ISSUE TITLE
Failed calling webhook "mutation.azure-workload-identity.io", context deadline exceeded on GKE

### ISSUE THREAD

**Issue by dotsuber** [Azure/azure-workload-identity#863]
**Describe the bug**

Installing Azure-Workload-Identity helm chart on GKE succeeded, but service accounts with the relevant label failed, and therefore their pods failed to launch.

**Steps To Reproduce**

1. Connect to GKE cluster, with default configurations.
2. Helm install Azure-Workload-Identity: 
helm upgrade --install workload-identity-webhook azure-workload-identity/workload-identity-webhook --namespace azure-workload-identity-system --set azureTenantID=TENANT_ID --wait --version 1.0.0
3. Helm install a pod with a label:
azure.workload.identity/use: "true"

**Expected behavior**

The pod should get the relevant info injected using the Azure-Workload-Identity Mutating Admission Webhook. That action fails and the pod never launches.

**Logs**

Logs taken from the K8s events:
36s         Warning   FailedCreate        replicaset/pod-7c749d6c8f   Error creating: Internal error occurred: failed calling webhook "mutation.azure-workload-identity.io": failed to call webhook: Post "https://azure-wi-webhook-webhook-service.azure-workload-identity-system.svc:443/mutate-v1-pod?timeout=10s": dial tcp 10.244.2.18:9443: i/o timeout
6s          Warning   FailedCreate        replicaset/pod-7c749d6c8f   Error creating: Internal error occurred: failed calling webhook "mutation.azure-workload-identity.io": failed to call webhook: Post "https://azure-wi-webhook-webhook-service.azure-workload-identity-system.svc:443/mutate-v1-pod?timeout=10s": context deadline exceeded

**Environment**
GKE 1.24.10-gke.2300, running on Linux.
Google Image type: Container-Optimized OS with containerd (cos_containerd)

**Comment by aramase** [comment]
> 36s Warning FailedCreate replicaset/pod-7c749d6c8f Error creating: Internal error occurred: failed calling webhook "mutation.azure-workload-identity.io": failed to call webhook: Post "[https://azure-wi-webhook-webhook-service.azure-workload-identity-system.svc:443/mutate-v1-pod?timeout=10s](https://azure-wi-webhook-webhook-service.azure-workload-identity-system.svc/mutate-v1-pod?timeout=10s)": dial tcp 10.244.2.18:9443: i/o timeout

@dotsuber Have you checked if the mutating webhook (mwh) pods are running and ready?

**Comment by aramase** [comment]
@dotsuber Any updates on the above?

**Comment by dotsuber** [comment]
The solution was to open port 9443 on GKE master firewall.
![image](https://user-images.githubusercontent.com/82760509/235339174-af45aa17-48af-4f50-a92e-0a6ea56c1270.png)
