### ISSUE TITLE
Flakiness during token fetch for authenticating against sqldb

### ISSUE THREAD

**Issue by poadhika** [Azure/azure-workload-identity#868]
While  migrating from aadpodidentity to workload identity, we also migrated to latest azure identity library but instead of using defaultazurecredentials , we used managedidentitycredential and we are noticing that it is causing flakiness during token fetch causing performance degradation. 

I understand that defaultazurecredentials is the recommended approach to fetch tokens to authenticate against sql db's. But using managedidentitycredential should also suffice. Is this known behaviour or am i missing anything?

**Comment by aramase** [comment]
> While migrating from aadpodidentity to workload identity, we also migrated to latest azure identity library but instead of using defaultazurecredentials , we used managedidentitycredential and we are noticing that it is causing flakiness during token fetch causing performance degradation.

@poadhika The Azure Workload Identity mutating webhook (mwh) is only during the pod admission path and is not involved in the token request flow. The token request implementation is part of the application abstracted by the SDK. I would recommend opening an issue in the GitHub repo of the SDK you're using with relevant error messages.

**Comment by aramase** [comment]
Closing this with https://github.com/Azure/azure-workload-identity/issues/868#issuecomment-1522480902. Feel free to reopen if you have any questions. Also, if you find something interesting from the SDK issue, comment here so it'll be helpful for other users who come across similar issue with the SDK.
