### ISSUE TITLE
Is it possible that mutating webhook include service account?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-workload-identity#906]
Hello,

As we need to create service account for every namespace its difficult to ask every team, especially in shared cluster, to include service account details in k8’s object definition. 

If possible, can we make any amendments in the mutating webhook so that it will read the service account details from any namespace and automatically include the details in the object yaml while creating it. 

Kind Regards,
Tanul

**Comment by aramase** [comment]
> If possible, can we make any amendments in the mutating webhook so that it will read the service account details from any namespace and automatically include the details in the object yaml while creating it.

@smartaquarius10 As I mentioned in the other threads, `ServiceAccount` are namespaced objects. Reading details from a service account in different namespace and populating env vars in pods in different namespace would be crossing security boundaries.
