### ISSUE TITLE
Documented version for workload identity support in java is incorrect, apparently no stable version supports it today

### ISSUE THREAD

**Issue by wba-josh-hetland** [Azure/azure-workload-identity#907]
**Describe the bug**
From: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html#azure-identity-sdk

Language | Library | Minimum Version
-- | -- | --
Go | azure-sdk-for-go | sdk/azidentity/v1.3.0-beta.1
C# | azure-sdk-for-net | Azure.Identity_1.5.0
JavaScript/TypeScript | azure-sdk-for-js | @azure/identity_2.0.0
Python | azure-sdk-for-python | azure-identity_1.7.0
Java | azure-sdk-for-java | azure-identity_1.4.0

Language	Library	Minimum Version
Go	[azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go)	[sdk/azidentity/v1.3.0-beta.1](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk/azidentity/v1.3.0-beta.1)
C#	[azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net)	[Azure.Identity_1.5.0](https://github.com/Azure/azure-sdk-for-net/releases/tag/Azure.Identity_1.5.0)
JavaScript/TypeScript	[azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js)	[@azure/identity_2.0.0](https://github.com/Azure/azure-sdk-for-js/releases/tag/@azure/identity_2.0.0)
Python	[azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python)	[azure-identity_1.7.0](https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-identity_1.7.0)
Java	[azure-sdk-for-java](https://github.com/Azure/azure-sdk-for-java)	[azure-identity_1.4.0](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-identity_1.4.0)

Suggests that the minimum version of the azure-identity library for Java is 1.4.0, however as of today the latest stable 1.8.2 does not include the classes for workload identity, and attempts to implement result in it falling to the EnvironmentCredential type.

Source file from 1.8.2 for builder: https://github.com/Azure/azure-sdk-for-java/blob/azure-identity_1.8.2/sdk/identity/azure-identity/src/main/java/com/azure/identity/DefaultAzureCredentialBuilder.java

It looks like the beta release 1.9 has the necessary support. This should be updated in the documentation to accurately reflect the necessary version to be using
**Steps To Reproduce**

**Expected behavior**
Documentation should point to a usable version as implied

**Logs**
23-04-28T15:01:46.082Z DEBUG 1 --- [           main] c.a.identity.ManagedIdentityCredential   : Azure Identity => Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID
2023-04-28T15:01:46.083Z DEBUG 1 --- [           main] c.a.identity.SharedTokenCacheCredential  : Azure Identity => Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID
2023-04-28T15:01:46.108Z DEBUG 1 --- [           main] c.azure.identity.EnvironmentCredential   : EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/environmentcredential/troubleshoot
com.azure.identity.CredentialUnavailableException: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at

**Environment**

- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-21T00:12:01Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure AKS
- OS (e.g: `cat /etc/os-release`): default
- Kernel (e.g. `uname -a`): default
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Additional context**

**Comment by aramase** [comment]
> Suggests that the minimum version of the azure-identity library for Java is 1.4.0, however as of today the latest stable 1.8.2 does not include the classes for workload identity, and attempts to implement result in it falling to the EnvironmentCredential type.

The minimum documented versions are for `DefaultAzureCredential` and those versions already support workload identity. In case of the current versions, workload identity is tied to managed identity credential but in the upcoming releases there will be a separate class for workload identity.

> It looks like the beta release 1.9 has the necessary support. This should be updated in the documentation to accurately reflect the necessary version to be using

We will update the docs with the latest release post May 8th when official releases are available. Closing this issue with https://github.com/Azure/azure-workload-identity/issues/920.
