### ISSUE TITLE
Can we use same federated credential for multiple service account?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/azure-workload-identity#919]
Hello,

In azure, we cannot make more than 20 federated credentials per managed identity. In shared cluster, it is common to have more than 20 namespaces in kubernetes. 

So, should we create a new identity for every 20 namespaces/service accounts. If yes, don't you think it's difficult to manage?

Kind Regards,
Tanul

**Comment by smartaquarius10** [comment]
Or else can do something like wildcard here

**Comment by aramase** [comment]
> In azure, we cannot make more than 20 federated credentials per managed identity. In shared cluster, it is common to have more than 20 namespaces in kubernetes.

So, should we create a new identity for every 20 namespaces/service accounts. If yes, don't you think it's difficult to manage?

This is an AAD limitation and here is the issue for wildcard - https://github.com/Azure/azure-workload-identity/issues/373. The recommendation from AAD team is to create a new managed identity. The wildcard support is being looked at it but there is no ETA.

@smartaquarius10 there have been quite a few issues with similar questions, so I would recommend checking out the issue history for similar questions. Also, feel free to use [discussions](https://github.com/Azure/azure-workload-identity/discussions/categories/q-a) for questions.
