### ISSUE TITLE
ManagedIdentityCredential authentication unavailable while triggering a function

### ISSUE THREAD

**Issue by arunmk-ms** [Azure/azure-workload-identity#930]
**Describe the bug**
We are getting the below exception while triggering an orchestration task. Is the issue due to an old version of `Azure.Identity` package?
`ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.`

**Logs**

```
{"Timestamp":"2023-05-04T02:00:07.7283976+00:00","Level":"Information","MessageTemplate":"{EventSourceEvent:l}","Properties":{"method":"ManagedIdentityCredential.GetToken","scopes":"[ https://storage.azure.com/.default ]","parentRequestId":"66a88af6-6099-43cc-831c-2c1d7c5b0439","exception":"Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.","EventSourceEvent":"ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 66a88af6-6099-43cc-831c-2c1d7c5b0439 Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.","EventId":{"Id":3,"Name":"GetTokenFailed"},"SourceContext":"Azure.Identity.1","resourceId":"/subscriptions/***/resourceGroups/***/providers/Microsoft.***Apis/workspaces/***/***services/***","resourceType":"Microsoft.***Apis/workspaces/***services","resourceName":"***/**","subscriptionId":"53fb361f-ff11-48d1-9817-35a17eefead5","workspaceResourceId":"/subscriptions/***/resourceGroups/***/providers/Microsoft.***Apis/workspaces/***","assemblyInformation":"0.1.3369+Branch.***.Sha.***.f1040648d99d1d335873854706acdbcc2d1abbb5","assemblyInformationOSS":"10.0.259+Branch.main.Sha.***.***","ImageRepository":"*.azurecr.io","ImageName":"***-functions","ImageTag":"0.1.3369"},"Renderings":{"EventSourceEvent":[{"Format":"l","Rendering":"ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 66a88af6-6099-43cc-831c-2c1d7c5b0439 Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found."}]}}
```

**Environment**
Production

- Kubernetes version (use `kubectl version`): 1.24
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Additional context**

**Comment by poadhika** [comment]
To add more context, we are still using the sidecar for the migration.  The exception seems to be coming from azure function host which is still using the azure identity 1.41. how can we get around this.

**Comment by aramase** [comment]
The minimum required versions for azure identity are documented here: https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html.

**Comment by poadhika** [comment]
But we are using side cars. Is that not enough?

**Comment by poadhika** [comment]
Still waiting on the response here. So looking at the release notes looks like this was added on 1.5.0 "Added support to ManagedIdentityCredential for Azure hosts using federated token exchange for managed identity."  Is it safe to say that the migration of the service that will use the azure functions is not possible until this version is supported by azure functions?

**Comment by poadhika** [comment]
is there any follow up on this issue? I am still waiting for answer.

**Comment by aramase** [comment]
@poadhika also started a teams thread so I'm closing this to avoid duplicate conversations.
