### ISSUE TITLE
Azure Identity SDK: Minimum Version is confusing

### ISSUE THREAD

**Issue by kevinharing** [Azure/azure-workload-identity#975]
**Describe the bug**
On [this](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#azure-identity-client-libraries) and [this](https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html) page, minimum versions to work with Azure Workload Identity are provided. However this is confusing as older versions of these SDKs work with AWI as well. For migration scenarios, I think this will hold a lot of people back, as according to these docs, one has to upgrade the workloads to include at least the specified version(s).

For example: I'm dealing with workloads in AKS created by different teams. In order to migrate to AWI (according to these docs), these workloads will have to be updated to a package released 3 weeks ago. This could take months.

My suggestion is specifying a `minimum recommended version` and a `minimum version` or something along those lines.

**Comment by kevinharing** [comment]
For a Microsoft supported piece of technology, it's awfully quiet in here.

**Comment by aramase** [comment]
> On [this](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#azure-identity-client-libraries) and [this](https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html) page, minimum versions to work with Azure Workload Identity are provided. However this is confusing as older versions of these SDKs work with AWI as well.

@kevinharing The older versions of the sdk work but have been changed significantly as part of their GA release for workload identity. So if you use the older version of the sdk, you'll need to rewrite the app again when moving to the newer version of the SDK. The current documented versions were recommended to us by the SDK team and they support `DefaultAzureCredential` and `WorkloadIdentityCredential` unlike the older versions which only support `DefaultAzureCredential` with workload identity bundled with `ManagedIdentityCredential`.

**Comment by kevinharing** [comment]
> > On [this](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#azure-identity-client-libraries) and [this](https://azure.github.io/azure-workload-identity/docs/topics/language-specific-examples/azure-identity-sdk.html) page, minimum versions to work with Azure Workload Identity are provided. However this is confusing as older versions of these SDKs work with AWI as well.
> 
> @kevinharing The older versions of the sdk work but have been changed significantly as part of their GA release for workload identity. So if you use the older version of the sdk, you'll need to rewrite the app again when moving to the newer version of the SDK. The current documented versions were recommended to us by the SDK team and they support `DefaultAzureCredential` and `WorkloadIdentityCredential` unlike the older versions which only support `DefaultAzureCredential` with workload identity bundled with `ManagedIdentityCredential`.

I understand the changes, but my point still stands. Going by the docs, this still would hold me back during migration. However, functionally the end result is the same with older versions of the SDKs. The thing that’s now unknown is how far back the older versions work with AWI. I suggest adding that (back) to the docs.
