### ISSUE TITLE
AAD POD Identity and Azure Workload Identity not working well on the same kubernetes cluster

### ISSUE THREAD

**Issue by kaman05010** [Azure/azure-workload-identity#995]
**Describe the bug**

AAD POD Identity and Azure Workload Identity not working well on the same kubernetes cluster

**Steps To Reproduce**
Deploy workload identity and Aad pods on the same AKS Environment

**Expected behavior**

**Logs**

Logs from demo pod:
kubectl logs demo                                               
I0616 09:13:25.464670       1 main.go:98] curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01": {"compute":{"location":"westeurope","name":"aks-agentpool-20470618-vmss_2","offer":"","osType":"Linux","placementGroupId":"f4fbb65f-6416-43fe-b849-a8848b474736","platformFaultDomain":"0","platformUpdateDomain":"0","publisher":"","resourceGroupName":"mc_denv.usr.kaman.rg_nkdev-books-kaman-aks_westeurope","sku":"","subscriptionId":"853fa6f0-659a-428c-b774-42c298ecaea3","tags":"aks-managed-createOperationID:24eb7a3d-95a8-4933-bdb5-3ffc8fa5fdc3;aks-managed-creationSource:vmssclient-aks-agentpool-20470618-vmss;aks-managed-kubeletIdentityClientID:ccf50362-34d6-4fd3-a4db-e9823d9f9b12;aks-managed-orchestrator:Kubernetes:1.24.10;aks-managed-poolName:agentpool;aks-managed-resourceNameSuffix:42768865;creator:kaman;env-creation:2023-06-06T18:57:49+05:30;env-name:nkdev-books-kaman-aks;nkdev-version:1.6.1","version":"","vmId":"c0ac6e40-30b7-414e-bdf2-1a6e93045067","vmSize":"Standard_DS4_v2"},"network":{"interface":[{"ipv4":{"ipAddress":[{"privateIpAddress":"10.106.237.6","publicIpAddress":""}],"subnet":[{"address":"10.106.237.0","prefix":"24"}]},"ipv6":{"ipAddress":[]},"macAddress":"6045BD9D4227"}]}}
E0616 09:14:45.465001       1 main.go:60] failed to refresh the service principal token, error: adal: Failed to execute the refresh request. Error = 'context deadline exceeded'
E0616 09:14:45.465031       1 main.go:41] Failed to acquire token from IMDS with identity client ID

Logs from MIC POD:
9:10:22.139838       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
I0616 09:11:00.301963       1 server.go:386] exception pod aad/aad-pod-identity-mic-55c5f48dbf-99pvx token handling
I0616 09:11:00.301981       1 server.go:329] fetching token for user assigned MSI for resource: https://management.azure.com/
I0616 09:11:00.805648       1 server.go:213] status (200) took 503745949 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.48
W0616 09:13:25.465187       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 1
W0616 09:13:25.765577       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 2
E0616 09:14:45.464983       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:14:45.465034       1 server.go:213] status (404) took 79999892611 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:16:25.467403       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:16:25.467439       1 server.go:213] status (404) took 79999843614 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:18:05.467860       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:18:05.467900       1 server.go:213] status (404) took 80000172660 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:19:45.466849       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:19:45.466890       1 server.go:213] status (404) took 80000275140 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:21:25.465811       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:21:25.465848       1 server.go:213] status (404) took 80000911658 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:23:05.465797       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:23:05.465838       1 server.go:213] status (404) took 79999928742 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:24:45.468940       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:24:45.468983       1 server.go:213] status (404) took 80000648522 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:26:25.467977       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:26:25.468024       1 server.go:213] status (404) took 80000957945 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:28:05.469821       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:28:05.469859       1 server.go:213] status (404) took 80000523180 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:29:45.466023       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:29:45.466060       1 server.go:213] status (404) took 80000108123 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:31:25.467848       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:31:25.467888       1 server.go:213] status (404) took 80000365222 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:33:05.466921       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:33:05.466968       1 server.go:213] status (404) took 80000329341 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:34:45.464881       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:34:45.464919       1 server.go:213] status (404) took 80000842325 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:36:25.467463       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:36:25.467502       1 server.go:213] status (404) took 80000247808 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:38:05.467867       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:38:05.467926       1 server.go:213] status (404) took 80001037371 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:39:45.467815       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:39:45.467853       1 server.go:213] status (404) took 80000135510 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:41:25.466866       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:41:25.466906       1 server.go:213] status (404) took 80000238263 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:43:05.466848       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:43:05.466892       1 server.go:213] status (404) took 80000107021 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:44:45.466046       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:44:45.466087       1 server.go:213] status (404) took 80000101977 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:46:25.468075       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:46:25.468113       1 server.go:213] status (404) took 80000124418 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:48:05.469999       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:48:05.470037       1 server.go:213] status (404) took 80000676645 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:49:45.465689       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:49:45.465728       1 server.go:213] status (404) took 79999840587 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49
E0616 09:51:25.467911       1 server.go:399] failed to get matching identities for pod: default/demo, error: context canceled
I0616 09:51:25.467953       1 server.go:213] status (404) took 80000825202 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.3.49

**Environment**

- Kubernetes versionv1.24.10
- Cloud provider AKS
- OS  Ubuntu 18.04.6 LTS

**Additional context**

**Comment by aramase** [comment]
Closing this issue as these logs are pod identity specific. I've shared the same migration guide: https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity on email too.
